### PR TITLE
order of operations should be install then config

### PR DESCRIPTION
**Pull request by teburd**
This fixes a bug with archlinux bootstrapping

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Need to test to see if this does not break all other distributions. Still, Thanks for the contribution.

**Comment by akoumjian** [comment]
Don't the debian/ubuntu packages start the services immediately after installing? This would break on those, I believe.

**Comment by s0undt3ch** [comment]
That was what I was thinking. So I think I'm back to my original though. Arch might need to be handled alone regarding this subject.

**Comment by s0undt3ch** [comment]
Err, got the tickets messed up.

This is not the proper fix. Sorry @bfrog. This is now handled in #168.

**Pull request closed without merging**
