### PR TITLE
ARM and Raspberry Pi

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by akoumjian** [comment]
I want a Raspberry Pi just to install salt on it. :smile:

**Comment by s0undt3ch** [comment]
Now you can using the bootstrap script too!

**Comment by majo83** [comment]
No, that does not work for me. Tried and failed, see by yourself (below). Operating system is Raspbian 2013/05.

```
root@raspberrypi:~# wget -O - http://bootstrap.saltstack.org | sudo sh
--2013-07-20 14:41:31--  http://bootstrap.saltstack.org/
Resolving bootstrap.saltstack.org (bootstrap.saltstack.org)... 74.208.29.198
Connecting to bootstrap.saltstack.org (bootstrap.saltstack.org)|74.208.29.198|:8                                                                             0... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/saltstack/salt-bootstrap/stable/bootstrap-salt.                                                                             sh [following]
--2013-07-20 14:41:32--  https://raw.github.com/saltstack/salt-bootstrap/stable/                                                                             bootstrap-salt.sh
Resolving raw.github.com (raw.github.com)... 103.245.223.133
Connecting to raw.github.com (raw.github.com)|103.245.223.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 105315 (103K) [text/plain]
Saving to: `STDOUT'

 0% [                                       ] 0           --.-K/s                                                                                            *  INFO: PIPED THROUGH sh -- Version 1.5.5
90% [==================================>    ] 95,379       302K/s
 *  INFO: System Information:
 *  INFO:   CPU:          ARMv6
 *  INFO:   CPU Arch:     armv6l
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   3.6.11+
 *  INFO:   Distribution: Debian 7.0

 *  INFO: Installing minion
100%[======================================>] 105,315      127K/s   in 0.8s

2013-07-20 14:41:38 (127 KB/s) - written to stdout [105315/105315]

 *  INFO: Found function install_debian_7_deps
 *  INFO: Found function install_debian_7_stable
 *  INFO: Found function install_debian_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_debian_7_deps()
OK
Get:1 http://raspberrypi.collabora.com wheezy Release.gpg [836 B]
Get:2 http://raspberrypi.collabora.com wheezy Release [2,035 B]
Get:3 http://mirrordirector.raspbian.org wheezy Release.gpg [490 B]
Get:4 http://archive.raspberrypi.org wheezy Release.gpg [490 B]
Get:5 http://mirrordirector.raspbian.org wheezy Release [14.4 kB]
Get:6 http://debian.saltstack.com wheezy-saltstack Release.gpg [836 B]
Get:7 http://archive.raspberrypi.org wheezy Release [7,200 B]
Get:8 http://raspberrypi.collabora.com wheezy/rpi armhf Packages [2,863 B]
Get:9 http://mirrordirector.raspbian.org wheezy/main armhf Packages [7,414 kB]
Get:10 http://debian.saltstack.com wheezy-saltstack Release [3,039 B]
Get:11 http://archive.raspberrypi.org wheezy/main armhf Packages [6,262 B]
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en_GB
Ign http://raspberrypi.collabora.com wheezy/rpi Translation-en
Ign http://archive.raspberrypi.org wheezy/main Translation-en_GB
Ign http://archive.raspberrypi.org wheezy/main Translation-en
Get:12 http://mirrordirector.raspbian.org wheezy/contrib armhf Packages [23.2 kB                                                                             ]
Get:13 http://mirrordirector.raspbian.org wheezy/non-free armhf Packages [48.0 k                                                                             B]
Get:14 http://mirrordirector.raspbian.org wheezy/rpi armhf Packages [569 B]
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en
Fetched 7,524 kB in 45s (164 kB/s)
W: Failed to fetch http://debian.saltstack.com/debian/dists/wheezy-saltstack/Rel                                                                             ease  Unable to find expected entry 'main/binary-armhf/Packages' in Release file                                                                              (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used                                                                              instead.
 * ERROR: Failed to run install_debian_7_deps()!!!

```

**Comment by majo83** [comment]
Update: I was able to install salt with pip on my Raspberry Pi. I had to install some of the dependencies manually however: 

```
# sudo apt-get install python-pip ; sudo apt-get install python-m2crypto ; sudo apt-get install swig ; sudo apt-get install python-dev ; pip install salt ;  
```

**Pull request merged**
