### PR TITLE
Final Neon Support Fix

### LINKED ISSUE #1395: Drone CI: which configuration file is in use and how to update it properly?
### Description of Issue/Question
This is a question: which file serves as a source of configuration for Drone CI,
`.drone.yml` or `.drone.jsonnet`?
If some of it is legacy, we need to drop it to avoid confusion and duplication of efforts. If the one of it is somehow generated from the other one, it should be documented how to make this conversion.

Also it appears that after the changes was made to the CI configs, all subsequent builds require manual approval from authorized person to kick off the build.

@s0undt3ch, could we change the CI behavior somehow to allow config changes applied automatically once being propagated to the `develop`? Because for now the build for the tip of `develop` is stuck:
https://drone.saltstack.com/saltstack/salt-bootstrap/282

### LINKED ISSUE #1400: Extend EOL checks for Fedora < 30
### Description of Issue/Question
Extend EOL checks for Fedora < 30

### LINKED ISSUE #1423: Arch Linux Post Neon
### Description of Issue/Question

bootstrap-salt.sh appears to try and use yum for arch linux based distributions.

### Setup
Using the standard arch platform in use on all the Saltstack-Formulas for testing with test-kitchen and docker:
```
- name: arch-base-latest-master-py2
    driver:
      image: netmanagers/salt-master-py2:arch-base-latest
      provision_command:
        - curl -o bootstrap-salt.sh -L https://bootstrap.saltstack.com
        - sh bootstrap-salt.sh -XdPbfrq -x python2 git master
      run_command: /usr/lib/systemd/systemd
```

### Steps to Reproduce Issue
Ran 'kitchen test' using the standard test-kitchen platform config above. Cut down results below:
```
INFO: Running version: 2020.01.29
 *  INFO: Executed by: 
 *  INFO: Command line: 'bootstrap-salt.sh -XdPbfrq -x python2 git master'
 *  INFO: Detected -x option. Using python2 to install Salt.

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.4.15-2-MANJARO
 *  INFO:   Distribution: Arch Linux 

 *  INFO: Installing minion
 *  INFO: Daemons will not be started

 *  WARN: Post Neon git based installations will always install salt and it's dependencies using pip
 *  WARN: You have 10 seconds to cancel and stop the bootstrap process

 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_arch_linux_git
 *  INFO: Found function install_arch_linux_git_post
 *  INFO: Found function install_arch_linux_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Forced shallow cloning of git repository.
 *  INFO: Attempting to shallow clone master from Salt's repository https://github.com/saltstack/salt.git
Cloning into 'salt'...
 *  INFO: Cloning Salt's git repository succeeded
 *  INFO: Running config_salt()
 *  INFO: Running install_arch_linux_git()
bootstrap-salt.sh: line 2021: yum: command not found
 * ERROR: Failed to run install_arch_linux_git()!!!
STDERR: The command '/bin/sh -c sh bootstrap-salt.sh -XdPbfrq -x python2 git master' returned a non-zero code: 1
---- End output of docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200201-10013-fnw37c . ----
Ran docker -H unix:///var/run/docker.sock build -f Dockerfile-kitchen20200201-10013-fnw37c . returned 1] on arch-desktop-arch-base-latest-master-py2
```

### Versions and Systems
See top of output above.

I could be completely wrong, but I think it may relate to this extract of bootstrap-salt.sh:
```
    # Install pip and pip dependencies
    if ! __check_command_exists "${_pip_cmd} --version"; then
        __PACKAGES="${_py_pkg}-pip gcc"
        # shellcheck disable=SC2086
        if [ "$DISTRO_NAME_L" = "debian" ];then
            __PACKAGES="${__PACKAGES} ${_py_pkg}-dev"
            __apt_get_install_noinput ${__PACKAGES} || return 1
        else
            __PACKAGES="${__PACKAGES} ${_py_pkg}-devel"
            __yum_install_noinput ${__PACKAGES} || return 1
        fi

    fi
```
It appears to attempt to use either apt or yum only as install methods.
I appreciate that Arch Linux isnt officially supported, and I appreciate that I could be entirely wrong in my assessment.

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
See title.
Additionally:
* Drop support for Fedora < 30
* Drop support for Debian < 8
* Adds preliminary support for Fedora 32, although disabled since it defaults to Py3.8 which salt doesn't yet support
* Locks kitchen config for Arch Linux to python 2 since Arch is also on Py3.8

### What issues does this PR fix or reference?

Closes https://github.com/saltstack/salt-bootstrap/issues/1395
Closes https://github.com/saltstack/salt-bootstrap/issues/1400
Closes https://github.com/saltstack/salt-bootstrap/issues/1423
Closes https://github.com/saltstack/salt-bootstrap/pull/1381

### CODE REVIEW

**Comment by myii** [comment]
@s0undt3ch As we discussed in `#formulas` a couple of days back, the `fedora-31` image build that was failing then is now passing.  To be completely sure, I'm rerunning all of the jobs again anyway:

* https://travis-ci.org/myii/salt-image-builder/builds/644860865

**Review by twangboy — APPROVED** [review]

**Comment by s0undt3ch** [comment]
@myii Thank You! Please report back any problems.

**Comment by s0undt3ch** [comment]
@vutny see anything requiring changes?

**Review by vutny — APPROVED** [review]
Wow, this PR is huge!
I was unable to spot anything critical, and the Drone looks happy.
Well done, @s0undt3ch . Thanks.

**Comment by myii** [comment]
@s0undt3ch Just one note for you, which appears to be a regression:

* https://travis-ci.org/myii/template-formula/builds/644862005

These were all passing before this set of changes (not just this PR but the last batch of development).  It no longer allows us install the latest `master` on top of an existing pre-salted image.

However, I wouldn't like to see this PR blocked, though -- the current bootstrap script needs to be fixed since it's broken.  Hopefully this can be addressed in another PR.

**Comment by myii** [comment]
@s0undt3ch That last link was the wrong one.  I've redone the comparison, before and after:

* https://travis-ci.org/myii/template-formula/builds/645908860 -- all failing
  - This is using the version of the bootstrap from this PR's branch
* https://travis-ci.org/myii/template-formula/builds/645913121 -- all passing except `arch-base-latest`
  - This is based on a commit before these recent developments
  - https://github.com/saltstack/salt-bootstrap/blob/7b192471e63174dc6cfc26369d8b17b4d600abd0/bootstrap-salt.sh

All of the above are failures to build or find `pycrypto`.

**Comment by myii** [comment]
@s0undt3ch Just had a bit more time to test and I've established that the `pycrypto` regression was introduced by this commit: 39ed3f8cb1b0b2b27c4e6ba9099a7b2e2b0d90fb.

**Comment by s0undt3ch** [comment]
The upcoming Neon release, salt's master branch has now defaulted to setuptools.
With that change, and because we hit an issue when testing the package build process, we reverted back to using pycrypto, for which there isn't a wheel available.
As such, we must build it from source, which [seems to work](https://github.com/s0undt3ch/salt-bootstrap/actions/runs/34623164) (nevermind the opensuse, that a bad github actions workflow issue).

This is the whole reason why git bootstraps post Neon(which include Salt's master branch) are now done without system packages and only using pypi packages.
When I get some more time, I'll look at your CI pipeline to find out why its failing.

**Comment by myii** [comment]
@s0undt3ch OK, thanks for the explanation.  We'll just avoid using the bootstrap on top of the pre-salted images for the time being.

**Comment by s0undt3ch** [comment]
By pre-salted you mean salt has been installed before and it's not the master branch, correct?

**Comment by myii** [comment]
We're building pre-salted images to use with SaltStack Formulas, for numerous platforms and all supported releases of Salt + `master`.  This is the repo:

* https://github.com/netmanagers/salt-image-builder

To ensure our `master` testing is the very latest, we use the bootstrap on top.  We'll just avoid that going forward; we've got a Travis cron job that runs every week anyway, so it will be pretty recent in any case.

**Comment by s0undt3ch** [comment]
Ok. Thanks for all your help!

**Comment by myii** [comment]
You're welcome.  Any idea when this PR will be merged?

**Comment by s0undt3ch** [comment]
As soon as drone passes, its going to be merged and a sable release will be done right after.

**Comment by myii** [comment]
Excellent, appreciate all of the work you're putting in, @s0undt3ch.

**Pull request merged**
