### PR TITLE
Added support for Kali Linux.

### PR DESCRIPTION
**Pull request by valentinbud**
I don't know if I've used the best method to detect 
the Debian derivative so I kindly ask someone, smarter
than me, to take a look over the code :).

### CODE REVIEW

**Comment by ghost** [comment]
Merged build triggered.

**Comment by ghost** [comment]
Merged build started.

**Comment by s0undt3ch** [comment]
Unfortunately I'm going to have to close this issue... It's implemented [here](https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L885-L920). Could add support for Kali on that function and submit another pull request?

**Comment by valentinbud** [comment]
I have thought of that, but the function you pointed out is for Ubuntu derivatives not Debian ones. I have copy / pasted the function, changed the logic to have one for Debian.

**Comment by s0undt3ch** [comment]
Ahhhh stupid.... Sorry about my fast and wrong decision...

**Comment by ghost** [comment]
Build triggered.

**Comment by ghost** [comment]
Merged build triggered.

**Comment by ghost** [comment]
Merged build finished.

**Comment by ghost** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap/job/pr/job/build/26/

**Comment by ghost** [comment]
Build started.

**Comment by ghost** [comment]
Build finished.

**Comment by ghost** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap/job/pr/job/build/27/

**Pull request merged**
