### PR TITLE
Ability to change cache dir

### PR DESCRIPTION
**Pull request by clarkperkins**
When launching minions into AWS, often the root partition is not very big - only 8GB usually.  I've recently run into an issue with using `file.managed` to manage large files.  Since the files are cached, the root partition fills up and breaks things.

This PR allows users to change the cache dir to be somewhere with more space.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by jfindlay** [comment]
@clarkperkins, this is looking good.  Would you mind rebasing?  Thanks.

**Comment by clarkperkins** [comment]
@jfindlay done!

**Comment by jfindlay** [comment]
Thanks, @clarkperkins.

**Pull request merged**
