### PR TITLE
fix for opensuse15 if no lsb_release pkg

### LINKED ISSUE #1254: opensuse-15: No dependencies installation func found
### Description of Issue/Question

Error on OpenSUSE Leap 15 when `lsb-release` is not installed.

>  *  INFO: Found function daemons_running
>  * ERROR: No dependencies installation function found. Exiting...

### Setup
(Please provide relevant configs (Be sure to remove sensitive info).)

Instance: https://app.vagrantup.com/opensuse/boxes/openSUSE-15.0-x86_64
Procedure: https://docs.saltstack.com/en/2015.8/topics/tutorials/salt_bootstrap.html

### Steps to Reproduce Issue
```
vagrant@vagrant-openSUSE-Leap:~> sudo sh bootstrap-salt.sh -D
 *  INFO: Running version: 2018.04.25
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap-salt.sh -D'
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.12.14-lp150.12.4-default
 *  INFO:   Distribution: opensuse-leap 15.0

 * DEBUG: Binaries will be searched using the following $PATH: /usr/sbin:/usr/bin:/sbin:/bin
 *  INFO: Installing minion
 * DEBUG: install_opensuseleap_15_stable_deps not found....
 * DEBUG: install_opensuseleap_15_0_stable_deps not found....
 * DEBUG: install_opensuseleap_15_deps not found....
 * DEBUG: install_opensuseleap_15_0_deps not found....
 * DEBUG: install_opensuseleap_stable_deps not found....
 * DEBUG: install_opensuseleap_deps not found....
 * DEBUG: DEPS_INSTALL_FUNC=null
 * DEBUG: config_opensuseleap_15_stable_salt not found....
 * DEBUG: config_opensuseleap_15_0_stable_salt not found....
 * DEBUG: config_opensuseleap_15_salt not found....
 * DEBUG: config_opensuseleap_15_0_salt not found....
 * DEBUG: config_opensuseleap_stable_salt not found....
 * DEBUG: config_opensuseleap_salt not found....
 *  INFO: Found function config_salt
 * DEBUG: CONFIG_SALT_FUNC=config_salt
 * DEBUG: preseed_opensuseleap_15_stable_master not found....
 * DEBUG: preseed_opensuseleap_15_0_stable_master not found....
 * DEBUG: preseed_opensuseleap_15_master not found....
 * DEBUG: preseed_opensuseleap_15_0_master not found....
 * DEBUG: preseed_opensuseleap_stable_master not found....
 * DEBUG: preseed_opensuseleap_master not found....
 *  INFO: Found function preseed_master
 * DEBUG: PRESEED_MASTER_FUNC=preseed_master
 * DEBUG: install_opensuseleap_15_stable not found....
 * DEBUG: install_opensuseleap_15_0_stable not found....
 * DEBUG: install_opensuseleap_stable not found....
 * DEBUG: INSTALL_FUNC=null
 * DEBUG: install_opensuseleap_15_stable_post not found....
 * DEBUG: install_opensuseleap_15_0_stable_post not found....
 * DEBUG: install_opensuseleap_15_post not found....
 * DEBUG: install_opensuseleap_15_0_post not found....
 * DEBUG: install_opensuseleap_stable_post not found....
 * DEBUG: install_opensuseleap_post not found....
 * DEBUG: POST_INSTALL_FUNC=null
 * DEBUG: install_opensuseleap_15_stable_restart_daemons not found....
 * DEBUG: install_opensuseleap_15_0_stable_restart_daemons not found....
 * DEBUG: install_opensuseleap_15_restart_daemons not found....
 * DEBUG: install_opensuseleap_15_0_restart_daemons not found....
 * DEBUG: install_opensuseleap_stable_restart_daemons not found....
 * DEBUG: install_opensuseleap_restart_daemons not found....
 * DEBUG: STARTDAEMONS_INSTALL_FUNC=null
 * DEBUG: daemons_running_opensuseleap_15_stable not found....
 * DEBUG: daemons_running_opensuseleap_15_0_stable not found....
 * DEBUG: daemons_running_opensuseleap_15 not found....
 * DEBUG: daemons_running_opensuseleap_15_0 not found....
 * DEBUG: daemons_running_opensuseleap_stable not found....
 * DEBUG: daemons_running_opensuseleap not found....
 *  INFO: Found function daemons_running
 * DEBUG: DAEMONS_RUNNING_FUNC=daemons_running
 * DEBUG: install_opensuseleap_15_stable_check_services not found....
 * DEBUG: install_opensuseleap_15_0_stable_check_services not found....
 * DEBUG: install_opensuseleap_15_check_services not found....
 * DEBUG: install_opensuseleap_15_0_check_services not found....
 * DEBUG: install_opensuseleap_stable_check_services not found....
 * DEBUG: install_opensuseleap_check_services not found....
 * DEBUG: CHECK_SERVICES_FUNC=null
 * ERROR: No dependencies installation function found. Exiting...
 * DEBUG: Removing the logging pipe /tmp/bootstrap-salt.logpipe
```

### Versions and Systems
(`salt --versions-report`, `bootstrap-salt.sh -v`, system type and version,
cloud/VM provider as appropriate.)

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### What does this PR do?
If `lsb-release` is not found on OpenSuse Leap 15.0 then bootstrap fails. 

However, OpenSUSE now ships an`/etc/os-release` file so can be used instead.

### What issues does this PR fix or reference?
Fixes #1254  and compliments #1244 (merged)

### Previous Behavior
Remove this section if not relevant

### New Behavior

```
vagrant@vagrant-openSUSE-Leap:~> sudo sh bootstrap-salt.sh git develop
 *  INFO: Running version: 2018.04.25
 *  INFO: Executed by: sh
 *  INFO: Command line: 'bootstrap-salt.sh git develop'
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.12.14-lp150.12.4-default
 *  INFO:   Distribution: opensuse 15.0

 *  INFO: Installing minion
 *  INFO: Found function install_opensuse_git_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_opensuse_git
 *  INFO: Found function install_opensuse_git_post
 *  INFO: Found function install_opensuse_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_opensuse_check_services
 *  INFO: Running install_opensuse_git_deps()
File '/opensuse/openSUSE_Leap_15.0/systemsmanagement:saltstack:products.repo' not found on medium 'https://repo.saltstack.com/'
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
Problem encountered while trying to read the file at the specified URI:
ABORT request: Aborting requested by user
Repository 'openSUSE Non-OSS' is up to date.
Retrieving repository 'openSUSE OSS' metadata [..^C
Download (curl) error for 'http://download.opensuse.org/distribution/leap/15.0/repo/oss/repodata/repomd.xml':
Error code: User abort
Error message: Callback aborted

Abort, retry, ignore? [a/r/i/...? shows all options] (a): a
error]
Repository 'openSUSE OSS' is invalid.
```

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Thanks @noelmcloughlin!

This should fix https://github.com/saltstack/salt-jenkins/issues/1024, too. :)

**Comment by rallytime** [comment]
Oh, also @noelmcloughlin - we do have a check for [commit signing](https://help.github.com/articles/about-gpg/) in this repo. If you could set that up for future submissions, that would be greatly appreciated.

**Comment by noelmcloughlin** [comment]
Thanks @rallytime !!!   I'll setup the commit signing too

**Comment by rallytime** [comment]
For sure! That sounds great!

Thanks for contributing! :D

**Pull request merged**
