### PR TITLE
Adds GitFS dependencies for Ubuntu

### PR DESCRIPTION
**Pull request by ifnull**

### CODE REVIEW

**Comment by gravyboat** [comment]
The install_ubuntu_git_deps function is for installing packages that are required to do a checkout from git for Salt itself. It is not used for installing pip or gitpython as neither of those are required for salt to function. I previously asked a question regarding this over at issue https://github.com/saltstack/salt-bootstrap/issues/245 and an answer was provided regarding why changes such as this will not be approved.

**Comment by s0undt3ch** [comment]
I think I've mentioned this before on an issue or another pull request, but here it goes again.

The same way Salt supports git as a back-end to it's file roots and pillar, it also supports mercurial, subversion, amaon's S3, and this list might grow as time goes by.
So, I'm going to reject this pull request but the discussion is still open.

We have two choices.
1. If all distros support something like "optional", or "suggestions", which is unlikely, we can add a flag which installs those, all of them
2. We add a flag which accepts a list of packages to be installed, additionally.

I'm thinking of 2.

Thoughts?

**Comment by gravyboat** [comment]
I like the idea of accepting a list of packages to be installed. This would allow it to continue to be OS agnostic, and reduce the workload on constantly maintaining the names of rpms/debs or whatever else.

**Comment by s0undt3ch** [comment]
Yep!

**Pull request closed without merging**
