### PR TITLE
Fix #1035: detect and log errors earlier

### LINKED ISSUE #1035: Some INFO: lines not logged
### Description of Issue/Question
Some INFO lines are outputted prior to setting up the logging pipe.  This means that one cannot review the command line used to call salt-bootstrap.sh in the logfile itself, which would make it easier to re-run salt-bootstrap inside a vagrant vm, for git-based installs, as more commits are pushed.

### Versions and Systems
`INFO: Running version: 2017.01.10`

### PR DESCRIPTION
**Pull request by vutny**
### What does this PR do?
* Write out most of output to the logging pipe except usage info.
* Detect obvious errors before trying to check inconsistency in provided command line options.

### CODE REVIEW

**Review by rallytime — APPROVED** [review]
I think this looks good. Thanks for fixing this @vutny. 

Let's get @s0undt3ch to review this one as well, just in case I missed anything.

**Comment by rallytime** [comment]
Fixes #1035

**Comment by rallytime** [comment]
Just a bump for @s0undt3ch to look at this one.

**Comment by s0undt3ch** [comment]
Looks good to me too.

**Pull request merged**
