### PR TITLE
Fix install on Debian Docker images (fix runlevel problem #479)

### PR DESCRIPTION
**Pull request by ross-p**
@slafs @s0undt3ch rebased PR #493

### CODE REVIEW

**Comment by ghost** [comment]
Test PASSed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap/job/pr/job/build/92/

**Comment by remusao** [comment]
Hello,

It seems for Ubuntu (I used a 12.04) images the same fix should be applied to `__check_services_upstart()`.

**Comment by jfindlay** [comment]
@s0undt3ch, do we still need this fix?

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt-bootstrap/pull/455 should address this.

**Pull request closed without merging**
