### PR TITLE
allow override of all option variables

### PR DESCRIPTION
**Pull request by robnagler**
Rebased #834

### CODE REVIEW

**Comment by rallytime** [comment]
Thanks for resubmitting this, @robnagler. Can you take a look at/fix up the pylint failures? 

https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/916/job/lint/1/violations/file/bootstrap-salt.sh/

**Comment by robnagler** [comment]
Would you send the errors? I don't want to authorize Salt's Jenkins to access my account. Thanks.

**Comment by rallytime** [comment]
@robnagler Sure! I'm not sure why it says tests are passing now. But here's the output from the console on the pylint run:

```
16:00:56 Started by upstream project "bootstrap/pr/916/main-build" build number 1
16:00:56 originally caused by:
16:00:56  GitHub pull request #916 of commit e26721aefae1664ab8975f8cd8fc7974a864736c, no merge conflicts.
16:00:56 [EnvInject] - Loading node environment variables.
16:00:56 [EnvInject] - Preparing an environment for the build.
16:00:56 [EnvInject] - Keeping Jenkins system variables.
16:00:56 [EnvInject] - Keeping Jenkins build variables.
16:00:56 [EnvInject] - Evaluation the following Groovy script content: 
16:00:56 import com.saltstack.jenkins.Projects
16:00:56 
16:00:56 def projects = new Projects()
16:00:56 projects.setCommitStatusPre(currentBuild, 'ci/lint', out)
16:00:56 
16:00:56 def build_env_vars = currentBuild.getEnvironment()
16:00:56 
16:00:56 return [
16:00:56     VIRTUALENV_SETUP_STATE_NAME: 'projects.bootstrap.lint',
16:00:56     COMMIT_STATUS_CONTEXT: 'ci/lint'
16:00:56 ]
16:00:56 
16:00:56 
16:00:56 Setting Initial Commit Status to the current build
16:00:56 GitHub commit status is PENDING
16:00:57 GitHub commit status successfuly set for for saltstack/salt-bootstrap@e26721aefae1664ab8975f8cd8fc7974a864736c
16:00:57 [EnvInject] - Injecting contributions.
16:00:57 Building on master in workspace /var/lib/jenkins/jobs/bootstrap/jobs/pr/jobs/916/jobs/lint/workspace
16:00:57 
16:00:57 Deleting project workspace... 
16:00:57 Deleting project workspace... Copied 1 artifact from "Salt Bootstrap » Pull Requests » PR #916 » Clone Repository" build number 1
16:00:57 [workspace] $ /bin/sh /tmp/hudson3373404487777527234.sh
16:00:57 >>>>>>>>>>>>>> Decompress Workspace >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
16:00:57 12864 blocks
16:00:58 <<<<<<<<<<<<<< Decompress Workspace <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
16:00:58 [workspace] $ /bin/sh /tmp/hudson3879658195990119227.sh
16:00:58 >>>>>>>>>>>>>> Prepare Build Env >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
16:01:03 [WARNING ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
16:01:03 Could not access /etc/salt/pki/minion. Try running as user root.
16:01:03 <<<<<<<<<<<<<< Prepare Build Env <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
16:01:03 [workspace] $ /bin/sh -xe /tmp/hudson7713415429902066264.sh
16:01:03 + shellcheck -s sh -f checkstyle /var/lib/jenkins/jobs/bootstrap/jobs/pr/jobs/916/jobs/lint/workspace/bootstrap-salt.sh
16:01:03 + tee checkstyle.xml
16:01:08 <?xml version='1.0' encoding='UTF-8'?>
16:01:08 <checkstyle version='4.3'>
16:01:08 <file name='/var/lib/jenkins/jobs/bootstrap/jobs/pr/jobs/916/jobs/lint/workspace/bootstrap&#45;salt.sh' >
16:01:08 <error line='62' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;CONFIG&#95;ONLY may not be assigned&#44; but &#95;CONFIG&#95;ONLY is.' source='ShellCheck.SC2153' />
16:01:08 <error line='62' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='63' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;CURL&#95;ARGS may not be assigned&#44; but &#95;CURL&#95;ARGS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='63' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='64' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;CUSTOM&#95;MASTER&#95;CONFIG may not be assigned&#44; but &#95;CUSTOM&#95;MASTER&#95;CONFIG is.' source='ShellCheck.SC2153' />
16:01:08 <error line='64' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='65' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;CUSTOM&#95;MINION&#95;CONFIG may not be assigned&#44; but &#95;CUSTOM&#95;MINION&#95;CONFIG is.' source='ShellCheck.SC2153' />
16:01:08 <error line='65' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='66' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;CUSTOM&#95;REPO&#95;URL may not be assigned&#44; but &#95;CUSTOM&#95;REPO&#95;URL is.' source='ShellCheck.SC2153' />
16:01:08 <error line='66' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='67' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;DISABLE&#95;REPOS may not be assigned&#44; but &#95;DISABLE&#95;REPOS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='67' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='68' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;DISABLE&#95;SALT&#95;CHECKS may not be assigned&#44; but &#95;DISABLE&#95;SALT&#95;CHECKS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='68' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='69' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;DISABLE&#95;SSL may not be assigned&#44; but &#95;DISABLE&#95;SSL is.' source='ShellCheck.SC2153' />
16:01:08 <error line='69' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='70' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;DOWNSTREAM&#95;PKG&#95;REPO may not be assigned&#44; but &#95;DOWNSTREAM&#95;PKG&#95;REPO is.' source='ShellCheck.SC2153' />
16:01:08 <error line='70' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='71' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;ECHO&#95;DEBUG may not be assigned&#44; but &#95;ECHO&#95;DEBUG is.' source='ShellCheck.SC2153' />
16:01:08 <error line='71' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='72' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;ENABLE&#95;EXTERNAL&#95;ZMQ&#95;REPOS may not be assigned&#44; but &#95;ENABLE&#95;EXTERNAL&#95;ZMQ&#95;REPOS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='72' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='73' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;EPEL&#95;REPO may not be assigned&#44; but &#95;EPEL&#95;REPO is.' source='ShellCheck.SC2153' />
16:01:08 <error line='73' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='74' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;EPEL&#95;REPOS&#95;INSTALLED may not be assigned&#44; but &#95;EPEL&#95;REPOS&#95;INSTALLED is.' source='ShellCheck.SC2153' />
16:01:08 <error line='74' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='75' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;EXTRA&#95;PACKAGES may not be assigned&#44; but &#95;EXTRA&#95;PACKAGES is.' source='ShellCheck.SC2153' />
16:01:08 <error line='75' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='76' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;FETCH&#95;ARGS may not be assigned&#44; but &#95;FETCH&#95;ARGS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='76' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='77' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;FORCE&#95;OVERWRITE may not be assigned&#44; but &#95;FORCE&#95;OVERWRITE is.' source='ShellCheck.SC2153' />
16:01:08 <error line='77' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='78' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;FORCE&#95;SHALLOW&#95;CLONE may not be assigned&#44; but &#95;FORCE&#95;SHALLOW&#95;CLONE is.' source='ShellCheck.SC2153' />
16:01:08 <error line='78' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='79' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;GENTOO&#95;USE&#95;BINHOST may not be assigned&#44; but &#95;GENTOO&#95;USE&#95;BINHOST is.' source='ShellCheck.SC2153' />
16:01:08 <error line='79' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='80' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;HTTP&#95;PROXY may not be assigned&#44; but &#95;HTTP&#95;PROXY is.' source='ShellCheck.SC2153' />
16:01:08 <error line='80' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='81' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;INSECURE&#95;DL may not be assigned&#44; but &#95;INSECURE&#95;DL is.' source='ShellCheck.SC2153' />
16:01:08 <error line='81' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='82' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;INSTALL&#95;CLOUD may not be assigned&#44; but &#95;INSTALL&#95;CLOUD is.' source='ShellCheck.SC2153' />
16:01:08 <error line='82' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='83' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;INSTALL&#95;MASTER may not be assigned&#44; but &#95;INSTALL&#95;MASTER is.' source='ShellCheck.SC2153' />
16:01:08 <error line='83' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='84' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;INSTALL&#95;MINION may not be assigned&#44; but &#95;INSTALL&#95;MINION is.' source='ShellCheck.SC2153' />
16:01:08 <error line='84' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='85' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;INSTALL&#95;SYNDIC may not be assigned&#44; but &#95;INSTALL&#95;SYNDIC is.' source='ShellCheck.SC2153' />
16:01:08 <error line='85' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='86' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;KEEP&#95;TEMP&#95;FILES may not be assigned&#44; but &#95;KEEP&#95;TEMP&#95;FILES is.' source='ShellCheck.SC2153' />
16:01:08 <error line='86' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='87' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;LIBCLOUD&#95;MIN&#95;VERSION may not be assigned&#44; but &#95;LIBCLOUD&#95;MIN&#95;VERSION is.' source='ShellCheck.SC2153' />
16:01:08 <error line='87' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='88' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;NO&#95;DEPS may not be assigned&#44; but &#95;NO&#95;DEPS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='88' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='89' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;PIP&#95;ALL may not be assigned&#44; but &#95;PIP&#95;ALL is.' source='ShellCheck.SC2153' />
16:01:08 <error line='89' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='90' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;PIP&#95;ALLOWED may not be assigned&#44; but &#95;PIP&#95;ALLOWED is.' source='ShellCheck.SC2153' />
16:01:08 <error line='90' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='91' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;QUIET&#95;GIT&#95;INSTALLATION may not be assigned&#44; but &#95;QUIET&#95;GIT&#95;INSTALLATION is.' source='ShellCheck.SC2153' />
16:01:08 <error line='91' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='92' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SALTSTACK&#95;REPO&#95;URL may not be assigned&#44; but &#95;SALTSTACK&#95;REPO&#95;URL is.' source='ShellCheck.SC2153' />
16:01:08 <error line='92' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='93' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SALT&#95;CACHE&#95;DIR may not be assigned&#44; but &#95;SALT&#95;CACHE&#95;DIR is.' source='ShellCheck.SC2153' />
16:01:08 <error line='93' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='94' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SALT&#95;ETC&#95;DIR may not be assigned&#44; but &#95;SALT&#95;ETC&#95;DIR is.' source='ShellCheck.SC2153' />
16:01:08 <error line='94' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='95' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SALT&#95;GIT&#95;CHECKOUT&#95;DIR may not be assigned&#44; but &#95;SALT&#95;GIT&#95;CHECKOUT&#95;DIR is.' source='ShellCheck.SC2153' />
16:01:08 <error line='95' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='96' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SALT&#95;MASTER&#95;ADDRESS may not be assigned&#44; but &#95;SALT&#95;MASTER&#95;ADDRESS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='96' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='97' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SALT&#95;MINION&#95;ID may not be assigned&#44; but &#95;SALT&#95;MINION&#95;ID is.' source='ShellCheck.SC2153' />
16:01:08 <error line='97' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='99' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SIMPLIFY&#95;VERSION may not be assigned&#44; but &#95;SIMPLIFY&#95;VERSION is.' source='ShellCheck.SC2153' />
16:01:08 <error line='99' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='100' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='101' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;START&#95;DAEMONS may not be assigned&#44; but &#95;START&#95;DAEMONS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='101' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='102' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;TEMP&#95;CONFIG&#95;DIR may not be assigned&#44; but &#95;TEMP&#95;CONFIG&#95;DIR is.' source='ShellCheck.SC2153' />
16:01:08 <error line='102' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='103' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;TEMP&#95;KEYS&#95;DIR may not be assigned&#44; but &#95;TEMP&#95;KEYS&#95;DIR is.' source='ShellCheck.SC2153' />
16:01:08 <error line='103' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='104' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;UPGRADE&#95;SYS may not be assigned&#44; but &#95;UPGRADE&#95;SYS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='104' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='105' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;VIRTUALENV&#95;DIR may not be assigned&#44; but &#95;VIRTUALENV&#95;DIR is.' source='ShellCheck.SC2153' />
16:01:08 <error line='105' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='106' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;WGET&#95;ARGS may not be assigned&#44; but &#95;WGET&#95;ARGS is.' source='ShellCheck.SC2153' />
16:01:08 <error line='106' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='109' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;PKI&#95;DIR may not be assigned&#44; but &#95;PKI&#95;DIR is.' source='ShellCheck.SC2153' />
16:01:08 <error line='109' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='110' column='3' severity='warning' message='Possible misspelling&#58; BS&#95;SALT&#95;REPO&#95;URL may not be assigned&#44; but &#95;SALT&#95;REPO&#95;URL is.' source='ShellCheck.SC2153' />
16:01:08 <error line='110' column='3' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 <error line='3397' column='10' severity='info' message='Double quote to prevent globbing and word splitting.' source='ShellCheck.SC2086' />
16:01:08 </file>
16:01:08 </checkstyle>
16:01:08 + exit 1
16:01:08 Build step 'Execute shell' marked build as failure
16:01:08 Setting Commit Status to the current build result
16:01:08 GitHub commit status context: ci/lint
16:01:08 GitHub commit status is ERROR
16:01:09 ERROR: Failed to evaluate groovy script.
16:01:09 groovy.lang.MissingPropertyException: No such property: msg for class: com.saltstack.jenkins.projects.Bootstrap
16:01:09    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:50)
16:01:09    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setGroovyObjectProperty(ScriptBytecodeAdapter.java:530)
16:01:09    at com.saltstack.jenkins.Project.setCommitStatusPost(Project.groovy:222)
16:01:09    at com.saltstack.jenkins.Project$setCommitStatusPost.call(Unknown Source)
16:01:09    at com.saltstack.jenkins.Projects.setCommitStatusPost(Projects.groovy:76)
16:01:09    at com.saltstack.jenkins.Projects$setCommitStatusPost.call(Unknown Source)
16:01:09    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
16:01:09    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
16:01:09    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
16:01:09    at Script1.run(Script1.groovy:4)
16:01:09    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:580)
16:01:09    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:618)
16:01:09    at groovy.lang.GroovyShell.evaluate(GroovyShell.java:589)
16:01:09    at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:166)
16:01:09    at org.jvnet.hudson.plugins.groovypostbuild.GroovyPostbuildRecorder.perform(GroovyPostbuildRecorder.java:361)
16:01:09    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
16:01:09    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
16:01:09    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
16:01:09    at hudson.model.Build$BuildExecution.post2(Build.java:185)
16:01:09    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
16:01:09    at hudson.model.Run.execute(Run.java:1763)
16:01:09    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
16:01:09    at hudson.model.ResourceController.execute(ResourceController.java:98)
16:01:09    at hudson.model.Executor.run(Executor.java:410)
16:01:09 Build step 'Groovy Postbuild' marked build as failure
16:01:09 Archiving artifacts
16:01:09 [BFA] Scanning build for known causes...
16:01:09 [BFA] No failure causes found
16:01:09 [BFA] Done. 0s
16:01:09 Finished: FAILURE
```

**Comment by robnagler** [comment]
If you want to toss this commit that's fine. I don't have time to work on
it.

**Comment by rallytime** [comment]
@robnagler Ok, no worries. I'll close this for now, but definitely feel free to re-submit this when you have a change to look at this again.

**Pull request closed without merging**
