### PR TITLE
feat: add detection and functions for AlmaLinux and Rocky Linux (fixes #1803)

### LINKED ISSUE #1803: How to bootstrap Salt on RockyLinux?
### Description of Issue/Question
I need to bootstrap Salt on RockyLinux, but I cannot get it working.
I need some help, please

### Setup
RockyLinux in Vagrant

### Steps to Reproduce Issue
1. downloaded bootstrap-salt.sh from develop branch
2. ran the command: `./bootstrap-salt.sh -x python3 -MPfq git develop'`

```
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.18.0-348.2.1.el8_5.x86_64
 *  INFO:   Distribution: Rocky 8.5

 *  INFO: Installing minion
 *  INFO: Installing master
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...
```

### Versions and Systems
```./bootstrap-salt.sh -v
./bootstrap-salt.sh -- Version 2021.09.17```

### PR DESCRIPTION
**Pull request by myii**
### What does this PR do?

```console
feat(bootstrap-salt): add AlmaLinux detection and functions
feat(bootstrap-salt): add Rocky Linux detection and functions
```

* Add detection/functions for both AlmaLinux and Rocky Linux.
* Fix #1803.

---

```console
ci(kitchen): use official Rocky Linux image on Docker Hub
```

* Official image is now available:
  - https://hub.docker.com/_/rockylinux?tab=tags

---

```console
ci(rockylinux): add `3004` testing (`stable` and `git`)
```

* Rocky Linux was added in `3004`:
  - https://github.com/saltstack/salt/pull/59682

---

```console
ci(gemfile+lock): update to latest versions
```

* Recommended to check-in `Gemfile.lock`:
  - https://bundler.io/v2.3/guides/bundler_sharing.html

---

```console
ci: remove `centos-8` (EOL)
```

* https://www.centos.org/centos-linux-eol/
  - "CentOS Linux 8 will reach End Of Life (EOL) on December 31st, 2021."

---

```console
ci: remove `fedora-33` (EOL)
```

* https://docs.fedoraproject.org/en-US/releases/eol/
  - Release:   Fedora Linux 33
  - EOL since: 2021-11-30

---

```console
ci(kitchen): set `LEGACY` crypto policy on Fedora (get `35` working)
```

* Using successfully in the `salt-image-builder` for almost a year now:
  - https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/commit/ac145f3022a13
* After adding this commit, these three instances are passing now:
  - `Fedora 35 v3002 Py3 Git`
  - `Fedora 35 v3003 Py3 Git`
  - `Fedora 35 Latest packaged release`

---

### What issues does this PR fix or reference?

* #1803.

### Previous Behavior

```console

*  INFO: System Information:
*  INFO:   CPU:          GenuineIntel
*  INFO:   CPU Arch:     x86_64
*  INFO:   OS Name:      Linux
*  INFO:   OS Version:   5.11.0-1027-azure
*  INFO:   Distribution: CentOS 8.5
```

* Both AlmaLinux and Rocky Linux were being detected as CentOS.

### CODE REVIEW

**Comment by maneamarius** [comment]
I've tested your PR and works with Alma, but still does not work with Rocky
(output from Vagrant)

```The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap_salt.sh  -F -c /tmp

Stdout from the command:

 *  INFO: Running version: 2021.09.17
 *  INFO: Executed by: 
 *  INFO: Command line: '/tmp/bootstrap_salt.sh -F -c /tmp'
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.18.0-348.2.1.el8_5.x86_64
 *  INFO:   Distribution: Rocky 8.5

 *  INFO: Installing minion
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function daemons_running
 * ERROR: No dependencies installation function found. Exiting...


Stderr from the command:
```

If you need to reproduce it, the following steps are needed (should work either on Windows or Linux machine (I use Ubuntu):
- install Vagrant
- install Virtualbox
- create a file called `Vagrantfile` with the following content:
- 
```
Vagrant.configure("2") do |config|
  config.vm.box = "bento/rockylinux-8"
end
```

- run `vagrant up`
- run `vagrant ssh`
- run the bostrap-salt.sh script inside the VM

**Comment by myii** [comment]
@maneamarius Thanks for testing.

I've found the difference; the Vagrant box has the `lsb_release` command available, so it enters the first `if` block instead.  Only needed [these two lines](https://github.com/saltstack/salt-bootstrap/pull/1804/files#diff-2dcd158d5c893c2ff2ca26cfb33f98d723db0ced5c291be99d523faf5cdc5921R1031-R1032) to fix it.  While I've already tested it at my end, would you mind downloading the latest version I've just pushed to this PR?

**Comment by maneamarius** [comment]
I've retested, and it does work fine now!
Thanks a lot for your help!

**Comment by myii** [comment]
> If you need to reproduce it, the following steps are needed (should work either on Windows or Linux machine (I use Ubuntu):
> 
> * install Vagrant
> * install Virtualbox
> * create a file called `Vagrantfile` with the following content:
> 
> 
> ```
> Vagrant.configure("2") do |config|
>   config.vm.box = "bento/rockylinux-8"
> end
> ```
> 
> * run `vagrant up`
> * run `vagrant ssh`
> * run the bostrap-salt.sh script inside the VM

@maneamarius Thanks for sharing these steps.  There's also another way, making use of `test-kitchen`.

https://github.com/saltstack/salt-bootstrap/blob/e4855afb3c678912329a40d4685166943a210d07/kitchen.vagrant.yml#L29-L32

Add this block:

```diff
+  - name: rockylinux-8
+    driver:
+      ssh:
+        shell: /bin/bash
```

Then run the Kitchen testing:

```console
$ KITCHEN_LOCAL_YAML=kitchen.vagrant.yml bundle exec kitchen test latest-rockylinux-8
```

**Comment by maneamarius** [comment]
Thank you, I will probably give test-kitchen a try as well, I'll need it as well..
Can we merge this PR please? So I can use it with Vagrant's `salt` provisioner :)

**Comment by myii** [comment]
> Can we merge this PR please?

@maneamarius I'm only a contributor here -- we'll have to wait for one of the maintainers to review and merge this PR.

> So I can use it with Vagrant's `salt` provisioner :)

I suppose you're referring to https://www.vagrantup.com/docs/provisioning/salt?  Looks interesting.

**Comment by myii** [comment]
@maneamarius You don't have to wait for this PR to be merged.  You can provide a custom bootstrap script:

* https://www.vagrantup.com/docs/provisioning/salt#bootstrap_script

**Comment by maneamarius** [comment]
> @maneamarius You don't have to wait for this PR to be merged. You can provide a custom bootstrap script:
> 
> * https://www.vagrantup.com/docs/provisioning/salt#bootstrap_script

I know, but it's not as pretty :))

**Review by krionbsd — APPROVED** [review]

**Pull request merged**
