### PR TITLE
move centos to python36, use python specified by -x to render passed config

### PR DESCRIPTION
**Pull request by bryceml**
### What does this PR do?
It fixes issue #1358 and updates centos7 to use python36 when python3 is specified in the repos since that is the version that provides the python3 binary now.
### What issues does this PR fix or reference?
#1358
### Previous Behavior

Script was out of date

### New Behavior
Script has been updated for repo changes and move to py3

### CODE REVIEW

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
__PACKAGES="${__PACKAGES} python36-PyYAML"

should be python36-pyyaml  I believe

**Comment by bryceml** [comment]
> __PACKAGES="${__PACKAGES} python36-PyYAML"
> 
> should be python36-pyyaml I believe

```bash
$ yum search python36-|grep -i yaml
python36-PyYAML.x86_64 : YAML parser and emitter for Python 3.6
python36-ruamel-yaml.x86_64 : YAML 1.2 loader/dumper package for Python
python36-yamlordereddictloader.noarch : YAML loader for PyYAML that maintains
```

**Review by dmurphy18 — CHANGES_REQUESTED** [review]
So have inconsistent feeling about Redhat messing up their naming, you will need to adjust to allow for Fedora and Redhat/Centos branches. 

Fedora 29
root@fedora-min:/home/dmurphy18# cat /etc/redhat-release 
Fedora release 29 (Twenty Nine)
root@fedora-min:/home/dmurphy18# dnf list | grep -i pyyaml
python2-pyyaml.x86_64              5.1-1.fc29                                                      @updates        
python3-pyyaml.x86_64              5.1-1.fc29                                                      @updates        
root@fedora-min:/home/dmurphy18# 

root@fedora-min:/home/dmurphy18# cat /etc/redhat-release 
Fedora release 30 (Thirty)
root@fedora-min:/home/dmurphy18# dnf list | grep -i pyyaml
python2-pyyaml.x86_64                                                  5.1-1.fc30                                                 @fedora         
python3-pyyaml.x86_64                                                  5.1-1.fc30                                                 @fedora         
root@fedora-min:/home/dmurphy18#

[root@Unknown ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.7 (Maipo)
[root@Unknown ~]# yum list | grep -i pyyaml
PyYAML.x86_64                                3.10-11.el7      @anaconda/7.7     
python27-PyYAML.x86_64                       3.10-15.el7      rhel-server-rhscl-7-beta-rpms
rh-python35-PyYAML.x86_64                    3.10-14.el7      rhel-server-rhscl-7-beta-rpms
rh-python36-PyYAML.x86_64                    3.12-1.el7       rhel-server-rhscl-7-beta-rpms
[root@Unknown ~]# 


root@Unknown:/etc/yum.repos.d# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
root@Unknown:/etc/yum.repos.d# yum list | grep -i pyyaml
PyYAML.x86_64                           3.10-11.el7                     @base   
python36-PyYAML.x86_64                  3.11-4.el7                      @epel   
PyYAML.x86_64                           3.11-2.el7                      salt-py3-test-latest
PyYAML-debuginfo.x86_64                 3.11-2.el7                      salt-py3-test-latest
python2-pyyaml.noarch                   3.10-0.el7                      epel    
python34-PyYAML.x86_64                  3.12-1.el7                      epel    
python36-PyYAML.x86_64                  3.12-1.el7                      epel    
root@Unknown:/etc/yum.repos.d#

**Comment by dmurphy18** [comment]
@bryceml And of course on Redhat 8
Red Hat Enterprise Linux release 8.0 (Ootpa)
[root@Unknown ~]# dnf list | grep -i pyyaml
python3-pyyaml.x86_64                                3.12-12.el8                                              @anaconda                        
python2-pyyaml.x86_64                                3.12-16.module+el8.0.0+2961+596d0223                     rhel-8-for-x86_64-appstream-rpms 
[root@Unknown ~]# 

Consistency such an easy concept but in practice a bit harder to do, have fun picking off Redhat 8 too

**Comment by bryceml** [comment]
@dmurphy18 This code should only be hit by centos 7 and 8 (py3 only) right? I shouldn't need to worry about fedora in this pr should I?  does the bootstrap script work for rhel? if it does, do we use epel or do we try to use redhat official packages?

I feel like it might be easier for this pr to be a joint effort if you want to add commits to this pr.

**Comment by dmurphy18** [comment]
@bryceml Line # 3485 deals with Fedora and it needs adjusting

**Comment by Ch3LL** [comment]
closing in favor of https://github.com/saltstack/salt-bootstrap/pull/1380

**Pull request closed without merging**
