### PR TITLE
Added to readme: supported OS SLES 11 SP3.

### PR DESCRIPTION
**Pull request by ghost**
I have tested salt-bootstrap on SUSE Linux Enterprise 11 SP3 and it works.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Is it OK to assume that enterprise sp1 and sp2 also works? If so, superb!

**Comment by s0undt3ch** [comment]
Nevermind. :smile:

**Comment by s0undt3ch** [comment]
Thanks!

**Comment by ghost** [comment]
Actually, I just noticed in https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh#L1324 that the script does not support 11 SP1 (contrary to what the README mentioned). We should remove SP1.

**Pull request merged**
