### PR TITLE
Improve SuSE support.

### PR DESCRIPTION
**Pull request by s0undt3ch**
Improve SuSE support.

We're still lacking proper SuSE 10 support.

Tests pass for openSUSE 12.x, SLES 11 SP1 and SP2.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@ixela, @aboe76: We now have proper openSuse 12.x, SLE 11 SP1 and SP2 support.

As you can see, there's no SLE 10 support.
Do you guys have a need for it?

I started an EC2 SLE10 SP3 machine(ami-16a3577f) and couldn't even install git:

```
  __|  __|_  )  SUSE Linux Enterprise
  _|  (     /       Server 10 SP3
 ___|\___|___|       x86 (32-bit)

For more information about using SUSE Linux Enterprise Server please see
http://www.novell.com/documentation/sles10/

Have a lot of fun...
ip-10-29-173-238:~ # zypper install git
Restoring system sources...
Parsing metadata for SLE10-SDK-SP3-Updates...
Parsing metadata for SLES10-SP3-Updates...
Parsing metadata for SLES10-SP3...
Parsing metadata for SLE10-SDK-SP3...
Parsing RPM database...
package 'git' not found
Summary:
Nothing to do.
```

So, if there's really a need, we can try adding support for it. If not, let's wait until someone requests support.

**Comment by aboe76** [comment]
Thanks for tour work

**Comment by s0undt3ch** [comment]
Anytime!

**Comment by ixela** [comment]
We no longer use SLES10 in production.

**Comment by s0undt3ch** [comment]
Cool!

**Pull request merged**
