### PR TITLE
fixing syntax errors

### PR DESCRIPTION
**Pull request by beardedeagle**
PR fixes the following:
- SC1073: Couldn't parse this test expression line 4434
- SC1073: Couldn't parse this test expression line 4451
- SC2173: SIGKILL/SIGSTOP can not be trapped line 553
- SC2170: Numerical -eq does not dereference in [..]. Expand or use string operator line 4395

### CODE REVIEW

**Comment by s0undt3ch** [comment]
What shell did you pass to shellcheck?

**Comment by beardedeagle** [comment]
@s0undt3ch shellcheck should grab the shebang at that top as far as I know so `sh`. Even if I force it run run against `sh`, just to be sure, I still run into the same issues that need to be corrected off of the develop branch.

`shellcheck --shell='sh' bootstrap-salt.sh`

Also removed the shebang and dropped to `sh` directly to run against

**Comment by vutny** [comment]
@beardedeagle :+1:

**Comment by vutny** [comment]
Ping @jfindlay
Looking forward for this to be merged.

**Comment by s0undt3ch** [comment]
Sorry I never got back to this..

**Pull request merged**
