### PR TITLE
Drop support for EOL distributions

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@KB1JWQ, @aboe76 I need you guys to take a look to see if I'm not messing up anything.

**Comment by quinnypig** [comment]
Looks good to me so long as your script "does the right thing" on a version string such as 10.04.4

**Comment by aboe76** [comment]
The message is alright. 
The logic is hard to grasp. 
If 12.1 is rol and 12.2 is still supported

**Comment by s0undt3ch** [comment]
On 25-09-2013 21:58, Corey Quinn wrote:

> Looks good to me so long as your script "does the right thing" on a
> version string such as 10.04.4
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/saltstack/salt-bootstrap/pull/237#issuecomment-25124230.

The last .4 is dropped

## 

Pedro Algarvio  _Pedro Algarvio_
Email me @algarvio.me mailto:pedro@algarvio.me // Find me on LinkedIn
http://www.linkedin.com/in/pedroalgarvio // Find me on Twitter
https://twitter.com/s0undt3ch // Find me on GitHub
https://github.com/s0undt3ch // Find me on BitBucket
https://bitbucket.org/s0undt3ch // Find me on Ohloh
https://www.ohloh.net/accounts/s0undt3ch // Like my work? Tip me on
GitTip https://www.gittip.com/s0undt3ch

**Comment by s0undt3ch** [comment]
@aboe76 rol?
My logic is saying below 12.1 versions are EOL.

**Comment by aboe76** [comment]
then it is fine by me...this should make your life much easier..
oh by the way, opensuse 13.1 has salt 0.16.4 as stable release.
upgrades as 0.17.0 will come from devel:languages:python repo.
don't know about backports to 13.1 but I will let you know.

**Comment by s0undt3ch** [comment]
@aboe76 Thanks, and for SuSE, which are EOL?

**Comment by aboe76** [comment]
@s0undt3ch, Suse Linux Enterprise is a different beast:
only info I could find is this page:
http://support.novell.com/lifecycle/?

in the search bar type: "suse linux enterprise Server"

I think you need to look at the general suppport date:

SUSE Linux Enterprise Server 10

General Support ends: 31 Jul 2013
Extended Support ends: 31 Jul 2016
Self-Support ends: 31 Jul 2016
Current version: SUSE Linux Enterprise Server 10 SP4
Replacement: SUSE Linux Enterprise Server 11

Service Pack Release First Customer Shipment Date
SUSE Linux Enterprise Server 10           17 Jul 2006
SUSE Linux Enterprise Server 10   SP1  18 Jun 2007
SUSE Linux Enterprise Server 10   SP2  19 May 2008
SUSE Linux Enterprise Server 10   SP3  12 Oct 2009
SUSE Linux Enterprise Server 10   SP4  12 Apr 2011

Suse linux enterprise server 11
General Support ends: 31 Mar 2016
Extended Support ends: 31 Mar 2019  
Self-Support ends : 31 Mar 2019
Current version SUSE Linux Enterprise Server 11 SP3

Service Pack Release First Customer Shipment Date           General Ends
SUSE Linux Enterprise Server 11           24 Mar 2009   31 Dec 2010
SUSE Linux Enterprise Server 11  SP1      02 Jun 2010   31 Aug 2012
SUSE Linux Enterprise Server 11  SP2      29 Feb 2012   31 Jan 2014
SUSE Linux Enterprise Server 11  SP3      01 Jul 2013   TBD

**Comment by s0undt3ch** [comment]
Ouch!

**Comment by aboe76** [comment]
I know, let suse linux enteprise be for the moment, I only package for suse 11 sp2 and up..
so support is still garanteed until 2016

**Comment by s0undt3ch** [comment]
@aboe76 So I'll drop support for SuSE 11 SP1 and lower, cool?

**Comment by aboe76** [comment]
Yes thanks
Op 26 sep. 2013 00:22 schreef "Pedro Algarvio" notifications@github.com
het volgende:

**Pull request merged**
