### PR TITLE
Added support to Elementary OS 0.2

### PR DESCRIPTION
**Pull request by wincus**
Tested on Elementary OS 0.2. I couldn't test it on other Ubuntu based flavours.

### CODE REVIEW

**Comment by ghost** [comment]
Merged build triggered.

**Comment by ghost** [comment]
Merged build started.

**Comment by ghost** [comment]
Merged build finished.

**Comment by ghost** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap/job/pr/job/build/17/

**Comment by s0undt3ch** [comment]
Sorry this took so long. It fell off my radar :frowning:

**Pull request merged**
