### PR TITLE
Merge #788

### PR DESCRIPTION
**Pull request by jfindlay**
Merge #788.

Ping @gdm85, @vutny.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
:+1:

**Comment by s0undt3ch** [comment]
Sorry, this needs a rebase now.

**Comment by gdm85** [comment]
Thanks for merging this; although I had checked the usage of `local` for dash, I understand why  it's not portable. Good to know.

**Comment by s0undt3ch** [comment]
@gdm85 the script needs to run in all shells and the only way to ensure that is to be fully POSIX compliant and unfortunately, `local` is not.

**Pull request merged**
