### PR TITLE
use versions specified in base.txt when doing pip installs

### PR DESCRIPTION
**Pull request by aflat**
### What does this PR do?
when doing pip installs it checks the requirements/base.txt to make sure it's installing the correct version

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-bootstrap/issues/1115 was the reference, but it doesn't fix it entirely.

### Previous Behavior
pip install would just install a version, not necessarily the version specified.

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @aflat thank you for adding this. There are, however, a couple of lint errors. Can you clean them up? Once that is fixed we can get this merged in.

https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/1116/job/lint/1/violations/file/bootstrap-salt.sh/

**Comment by aflat** [comment]
All cleaned up

**Comment by rallytime** [comment]
@aflat It looks like there is still one more error here. Mind taking another look?

https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/1116/job/lint/6/violations/file/bootstrap-salt.sh/

**Comment by aflat** [comment]
Sorry, got lost in the other lint errors when I was running shellcheck.

**Comment by rallytime** [comment]
No worries! Looks good now. :)

**Review by rallytime — APPROVED** [review]

**Pull request merged**
