### PR TITLE
Remove <<< bashism

### PR DESCRIPTION
**Pull request by The-Loeki**
`<<<` is a BASHim.

Every non-BASH shell borks on this.

### CODE REVIEW

**Comment by rallytime** [comment]
@The-Loeki Good catch! There are some pylint errors however that need to be cleaned up before we can get this in. Mind taking a look?

https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/1032/job/lint/1/violations/file/bootstrap-salt.sh/

**Comment by rallytime** [comment]
Hi @The-Loeki - It looks like there are a couple more lint violations here that need to be cleaned up. Can you take another shot?

https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/1032/job/lint/3/violations/file/bootstrap-salt.sh/

**Comment by The-Loeki** [comment]
handydandy toolie that `ShellCheck` thingy ;)

**Comment by rallytime** [comment]
@The-Loeki Indeed! Thanks for getting this cleaned up. :)

**Pull request merged**
