### PR TITLE
Update bootstrap shell CI/CD to utilize containers and clean up

### LINKED ISSUE #2038: Update bootstrap shell CI/CD to utilize containers and clean up
### Description of Issue/Question
Update bootstrap shell CI/CD to utilize containers and clean up

Need to enable CI/CD for shell bootstrap-salt for Linux and MacOS. Release v2024.11.07 was tested by hand in order to speed delivery with CI/CD testing disabled.  This issue tracks fixing CI/CD to utilize containers not that the AWS infrastructure that was previously used, is no longer available.

Limits of the v2024.11.07 release:
- Support for Broadcom packaging infrastructure, packaging.broadcom.com
- Photon OS support only for latest Salt, that is, Salt 3007.1 (problem with Photon support for repo file exclude parameter)
- Linux platforms only support latest major branch versions (similar to Salt Install Guide),  for example: 3006.9, 3007.1
- Windows and MacOS support minor branch versions, for example: 3006.8
- Future fixes for Linux minor versions of Salt will be forth-coming

TODO:

- Need to adjust Photon OS minor version support
- Need to adjust Linux OS minor version support
- Optimize script to eliminate duplication
- Remove support for OS which are no longer relevant, for example: gentoo

### PR DESCRIPTION
**Pull request by dmurphy18**
### What does this PR do?
https://github.com/saltstack/salt-bootstrap/issues/2038

### What issues does this PR fix or reference?
Fixes https://github.com/saltstack/salt-bootstrap/issues/2038

### CODE REVIEW

**Comment by ITJamie** [comment]
Why dropping almalinux for rocky?

**Comment by dmurphy18** [comment]
We made the decision to use Rocky during the summer, since it most closely aligns with RedHat, whereas seen differences in how AlmaLinux operates, esp. using alternatives.

New CI/CD for bootstrap is going to make use of salt-ci-containers (https://github.com/saltstack/salt-ci-containers), similar to the new pipelines being worked on, hence the change to leverage Rocky.  We were using Rocky for the last few months on AWS with Salt build pipelines, but AWS is gone now (Broadcom corp. mandate)

**Comment by dmurphy18** [comment]
Currently passing on Linux systemd enabled Ubuntu 22.04 container, waiting for rest of Salt CI Containers (https://github.com/saltstack/salt-ci-containers/pkgs/container/salt-ci-containers%2Ftesting/versions?filters%5Bversion_type%5D=tagged) to support systemd before removing debugging output and performing cleanup of code.

MacOS and Windows passing, just waiting on Linux before releasing

**Comment by dmurphy18** [comment]
Added testing on MacOS 14

**Comment by dmurphy18** [comment]
Hand tested Photon 5  by hand and adjusted for issues found

**Comment by dmurphy18** [comment]
Adding a comment and whoops , wrong button, hence reopen

**Pull request merged**
