### PR TITLE
Add hash verification information to installation instructions

### LINKED ISSUE #1043: Installation instructions should include hash verification
### Description of Issue/Question

There is no way to verify that the file downloaded is the correct one. The bootstrap installation procedure should list the correct SHA256 sum of the script or reference a file which contains that sum.

### PR DESCRIPTION
**Pull request by rallytime**
Fixes #1043

cc: @cachedout

### CODE REVIEW

**Review by vutny — COMMENTED** [review]
This is OK in general.

But it would be really nice to have a hash sum in a separate file and be able to verify it automatically (and generate it the same way).
For example:
```bash
curl -L https://bootstrap.saltstack.com/bootstrap-salt.sh.sha512 | sha512sum -c -
```

**Comment by rallytime** [comment]
@vutny Yes, I agree. I was thinking about doing it that way as well, but then I wasn't sure where to put it right now. We could add the sum files to repo.saltstack.com, one for each new release of the bootstrap script. This would be similar to how we do this for the windows executables: https://repo.saltstack.com/#windows

I think for now this is a good start, though, until we can get that added to repo.saltstack.com. I want to loop @Ch3LL in here for getting something like this added to the bootstrap release process. @Ch3LL what do you think?

**Comment by Ch3LL** [comment]
We could possibly just add it to bootstrap.saltstack.com but I would like to get @UtahDave 's input here since he is more familiar with how that is setup to see if this is a possibility. That way the sha is in the same subdomain.

**Comment by rallytime** [comment]
@Ch3LL Oh yes, you're right. The same subdomain is best. :) We're already doing this with the Windows sum files, so I think we should do this with the bootstrap releases as well.

**Comment by rallytime** [comment]
I think this is good for now from a bootstrap script perspective. We'll have to follow up with the file repo conversation at a later time.

**Pull request merged**
