### PR TITLE
Devuan support

### PR DESCRIPTION
**Pull request by ymasson**
### What does this PR do?
Add Devuan 1 and 2 support.

Devuan is Debian based

### What issues does this PR fix or reference?
Bootstrap of Cumulus fails with "End of life distributions are not supported"  #1162

### CODE REVIEW

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Thanks for fixing this @ymasson and welcome to Salt Bootstrap! :)

This looks good to me, but @vutny has been in this area of the code lately as well, so I'll request a review from him as well.

**Comment by ymasson** [comment]
No problem, the workaround details are in the issue #1162 .

**Comment by rallytime** [comment]
Fixes #1162

**Comment by ymasson** [comment]
Thank you

**Comment by rallytime** [comment]
@ymasson Thank you! And congrats on submitting your first bootstrap PR! 🎉

**Pull request merged**
