### PR TITLE
Fix sleep time option to recognize a numeric argument

### PR DESCRIPTION
**Pull request by vutny**
Silly bug, possibly introduced by wrong merge.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Oh, you been bumping the date. That's usually only right before merging to stable, but that's alright...

**Comment by s0undt3ch** [comment]
Could you take care of [this one](https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/766/job/lint/2/violations/file/bootstrap-salt.sh/) too since you're at it?

Thanks!

**Comment by vutny** [comment]
@s0undt3ch I've already fixed it in 1b9ea4f. Jenkins triggered job for wrong PR No 766 again, but the first attempt was correct.

**Comment by vutny** [comment]
Regarding the version bump, I thought that `develop` branch went far away from `stable` currently, and there is no way to determine the exact commit from bug reports...
Especially when people use `curl -L https://bootstrap.saltstack.com/develop ...`.

**Comment by s0undt3ch** [comment]
The only way to determine is the -dev in the end. If the version of stable and develop match, develop is more recent because of that suffix...

**Comment by vutny** [comment]
@s0undt3ch Acknowledged, thanks. Will add `-dev` suffix in further PRs.

**Comment by s0undt3ch** [comment]
No no. -dev is added automatically :)

**Comment by vutny** [comment]
@s0undt3ch Strange... I can't find where such thing happen... Maybe you meant this?

``` sh
 504 echowarn "Running the unstable version of ${__ScriptName}"
```

This line is commented in `stable`.

**Comment by s0undt3ch** [comment]
Hmm, yes, that's what I was referring to. Sorry.

**Pull request merged**
