### PR TITLE
Add python-gnupg dependency install for gpg render support.

### PR DESCRIPTION
**Pull request by christianchristensen**
xref: http://docs.saltstack.com/en/latest/ref/renderers/all/salt.renderers.gpg.html

### CODE REVIEW

**Comment by christianchristensen** [comment]
Idea here being support for [all renders](http://docs.saltstack.com/en/latest/ref/renderers/all/) should be supported at bootstrap.

When using a `#! jinja | yaml | gpg` template on initial run the `python-gnupg` dependency is needed.

**Comment by christianchristensen** [comment]
Note: this needs work for other systems deps.

**Comment by s0undt3ch** [comment]
I'm sorry for the trouble you had but this is not a hard dependency for salt, and, as such, it's not the script's responsibility to install it. Once salt is installed, you can use it to install the optional dependencies.

Again, I'm sorry for the trouble but I'm closing this PR.

**Comment by s0undt3ch** [comment]
There is a switch which allows you to install extra pip dependencies at bootstrap time.

**Comment by christianchristensen** [comment]
Thanks @s0undt3ch ! Saw the `-p` flag, for packages, and that seems to be a good way to handle this case.

**Pull request closed without merging**
