### PR TITLE
Improve documentation: document issues fetching script in Centos6

### PR DESCRIPTION
**Pull request by unicolet**
See discussion at #384

### CODE REVIEW

**Comment by ghost** [comment]
Merged build triggered.

**Comment by ghost** [comment]
Merged build started.

**Comment by ghost** [comment]
Merged build finished.

**Comment by ghost** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap/job/pr/job/build/22/

**Comment by s0undt3ch** [comment]
`(in FreeBSD >= 10)` is meant just for `fetch`

**Pull request merged**
