### PR TITLE
add support for repo.saltstack.com

### PR DESCRIPTION
**Pull request by jfindlay**
Adds support for debian 8, ubuntu 12,14, CentOS 5,6,7, and FreeBSD from https://repo.saltstack.com/.

### CODE REVIEW

**Comment by jfindlay** [comment]
@s0undt3ch, don't merge yet.  I need to make some changes to the FreeBSD support that should be done by about 17:00 UTC.

**Comment by jfindlay** [comment]
@s0undt3ch, this should be good to merge now.

**Comment by jfindlay** [comment]
Fixes #648, #659, #667, #668, #669, #672, #675.

**Comment by marek-obuchowicz** [comment]
Please make sure that it is also included somehow in the release process:
- the URL provided in README.md - https://bootstrap.saltstack.com/develop - points to some older version than current development branch
- it would be very helpful to have it merged in to master - salt-cloud is getting http://bootstrap.saltstack.org so this fix is not yet visible to users and for most use cases, unless someone finds this issue, still old version is installed

**Comment by tehmaspc** [comment]
@jfindlay 
ah sweet! thanks for this - was wondering when salt bootstrap was going to pull from the new repo.saltstack.com; I should just have to do a salt-cloud -u to get the benefit of this correct?

**Comment by jfindlay** [comment]
@marek-obuchowicz, we will be making a new bootstrap release soon, probably no later than the end of this week.  I have downloaded https://bootstrap.saltstack.com/develop and in my experiment it matches exactly the version of the script at 2edcbaf08091ab6f6ce8903cb48de7efac426fae, which is the current HEAD of the develop branch.

@tehmaspc, I think you are correct, but please report if not, thanks.

**Comment by virtualguy** [comment]
repo.saltstack.com doesn't have packages for the following architectures (which were on debian.saltstack.com):
- armel
- armhf
- i686
- mips

Of particular note to me, is this switch to repo.saltstack.com has broken bootstrapping in the raspberrypi (armhf). Is there plans to add the other architectures.

Should I open a fresh ticket or is there a better place to request architectures to be added to repo.saltstack.com?

**Comment by jfindlay** [comment]
@virtualguy, see https://github.com/saltstack/salt/issues/28742.

**Pull request merged**
