### PR TITLE
Add support for the upcoming Sodium release

### PR DESCRIPTION
**Pull request by s0undt3ch**
### What does this PR do?
Adds support for the upcoming Sodium release

### CODE REVIEW

**Comment by myii** [comment]
Nice, I'll start using this to build pre-salted images once this is merged.  A question though: shouldn't the test matrix be updated to include `3001` as well?

**Comment by s0undt3ch** [comment]
@myii Sodium is not released yet.
You might want to wait for that.
:)

**Comment by myii** [comment]
@s0undt3ch I understand, we're already building images for `master` anyway, so no problem having some `3001` images around for playing around with!  At least we'll already be prepared for the Sodium release once it's in place.

**Comment by s0undt3ch** [comment]
@myii For sure, just wanted to clear that out

**Pull request merged**
