### PR TITLE
make salt-syndic optional on salt bootstrap

### PR DESCRIPTION
**Pull request by sybix**
### What does this PR do?

Add the possibility of bootstraping Alpine Linux without salt-syndic

### What issues does this PR fix or reference?
#1188

### CODE REVIEW

**Review by vutny — APPROVED** [review]
Awesome @sybix ! Thanks.

**Review by rallytime — APPROVED** [review]

**Comment by rallytime** [comment]
Thank you @sybix and welcome! I love seeing new contributors jump into fixing bootstrap. :)

**Comment by bbczeuz** [comment]
Any plans to rebase https://bootstrap.saltstack.com to include this pull request? Without these fixes, the bootstrap script reliably fails on Alpine Linux (we use Alpine Linux for quick testing).

**Comment by rallytime** [comment]
@bbczeuz The script in bootstrap.saltstack.com will be updated when we do a release. We will hopefully be able to do that in the next couple of weeks.

Otherwise, you can pull from the develop branch here: https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

**Pull request merged**
