### PR TITLE
Allow for a more generic optional repository testing. Closes #402.

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Tagging @techhat, @nmadhok

**Comment by nmadhok** [comment]
Still fails using this bootstrap-script. I tried to test it by creating an instance on AWS and two instances on our local OpenStack implementation. 
Also, the log output is a little messed up. Notice

```
---> Package ope
npgm.x86_64 0:5.1.118-3.el6 will be installed
```

```
Installing for dependencies:
 openpgm               x86_64       5.1.118-3.el6          epel           165 k
 python-babel          noarch       0.9.4-5.1.el[DEBUG   ] npgm.x86_64 0:5.1.118-3.el6 will be installed
--> Finished Dependency Resolution
```

```
Installing for dependencies:
 openpgm               x86_64       5.1.118-3.el6          epel           165 k
 python-babel          noarch       0.9.4-5.1.el
6          os             1.4 M
 zeromq3               x86_64       3.2.4-1.el6            epel           334 k
```

```
Transaction Summary
================================================================================
Install       8 Package(s)
Upgrade       1 Package(s)

Total size: 3.1 M
Total download size: 1.3 M
Downloading Packages:
[DEBUG   ] 6          os             1.4 M
 zeromq3               x86_64       3.2.4-1.el6            epel           334 k

Transaction Summary
================================================================================
Install       8 Package(s)
Upgrade       1 Package(s)

Total size: 3.1 M
Total download size: 1.3 M
Downloading Packages:
```

Here's the complete log:

```
 *  INFO: /bin/sh /tmp/.saltcloud/deploy.sh -- Version 2014.04.16
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-431.1.2.el6.x86_64
 *  INFO:   Distribution: <R>ed <H>at <E>nterprise <L>inux 6.5

 *  INFO: Installing minion
 *  INFO: Found function install_red_hat_enterprise_linux_stable_deps
 *  INFO: Found function config_salt
[DEBUG   ]  *  INFO: /bin/sh /tmp/.saltcloud/deploy.sh -- Version 2014.04.16
 *  WARN: Running the unstable version of bootstrap-salt.sh

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   2.6.32-431.1.2.el6.x86_64
 *  INFO:   Distribution: <R>ed <H>at <E>nterprise <L>inux 6.5

 *  INFO: Installing minion
 *  INFO: Found function install_red_hat_enterprise_linux_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function install_red_hat_enterprise_linux_stable
 *  INFO: Found function install_red_hat_enterprise_linux_stable_post
 *  INFO: Found function install_red_hat_enterprise_linux_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_red_hat_enterprise_linux_stable_deps()
 *  INFO: Installing 'yum-tsflags' to test for package installation success
[DEBUG   ]  *  INFO: Found function install_red_hat_enterprise_linux_stable
 *  INFO: Found function install_red_hat_enterprise_linux_stable_post
 *  INFO: Found function install_red_hat_enterprise_linux_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Running install_red_hat_enterprise_linux_stable_deps()
 *  INFO: Installing 'yum-tsflags' to test for package installation success
Loaded plugins: product-id, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
[DEBUG   ] Loaded plugins: product-id, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
[DEBUG   ] Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5 will be installed
[DEBUG   ] Resolving Dependencies
--> Running transaction check
---> Package yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                 Arch        Version                Repository     Size
================================================================================
Installing:
 yum-plugin-tsflags      noarch      1.1.30-17.el6_5        optional       20 k

Transaction Summary
================================================================================
Install       1 Package(s)

Total download size: 20 k
Installed size: 20 k
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
[DEBUG   ] --> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                 Arch        Version                Repository     Size
================================================================================
Installing:
 yum-plugin-tsflags      noarch      1.1.30-17.el6_5        optional       20 k

Transaction Summary
================================================================================
Install       1 Package(s)

Total download size: 20 k
Installed size: 20 k
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : yum-plugin-tsflags-1.1.30-17.el6_5.noarch                    1/1[DEBUG   ] 

  Verifying  : yum-plugin-tsflags-1.1.30-17.el6_5.noarch                    1/1[DEBUG   ]  
  Verifying  : yum-plugin-tsflags-1.1.30-17.el6_5.noarch                    1/1


Installed:
  yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5                                   

Complete!
[DEBUG   ]  

Installed:
  yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5                                   

Complete!
Loaded plugins: product-id, subscription-manager, tsflags
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
[DEBUG   ] Loaded plugins: product-id, subscription-manager, tsflags
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Setting up Install Process
Package chkconfig-1.3.49.3-2.el6_4.1.x86_64 already installed and latest version
Package matching PyYAML-3.10-3.el6.x86_64 already installed. Checking for update.
Package m2crypto-0.20.2-9.el6.x86_64 already installed and latest version
[DEBUG   ] Package chkconfig-1.3.49.3-2.el6_4.1.x86_64 already installed and latest version
Package matching PyYAML-3.10-3.el6.x86_64 already installed. Checking for update.
Package m2crypto-0.20.2-9.el6.x86_64 already installed and latest version
Resolving Dependencies
--> Running transaction check
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be installed
---> Package python-jinja2.x86_64 0:2.2.1-2.el6_5 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.2.1-2.el6_5.x86_64
---> Package python-msgpack.x86_64 0:0.1.13-3.el6 will be installed
---> Package python-requests.noarch 0:1.1.0-3.1.1.el6 will be updated
---> Package python-requests.noarch 0:1.1.0-4.el6 will be an update
---> Package python-zmq.x86_64 0:2.2.0.1-1.el6 will be installed
--> Processing Dependency: libzmq.so.3()(64bit) for package: python-zmq-2.2.0.1-1.el6.x86_64
---> Package yum-utils.noarch 0:1.1.30-17.el6_5 will be installed
--> Running transaction check
---> Package python-babel.noarch 0:0.9.4-5.1.el6 will be installed
---> Package zeromq3.x86_64 0:3.2.4-1.el6 will be installed
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.4-1.el6.x86_64
--> Running transaction check
---> Package ope[DEBUG   ] Resolving Dependencies
--> Running transaction check
---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be installed
---> Package python-jinja2.x86_64 0:2.2.1-2.el6_5 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.2.1-2.el6_5.x86_64
---> Package python-msgpack.x86_64 0:0.1.13-3.el6 will be installed
---> Package python-requests.noarch 0:1.1.0-3.1.1.el6 will be updated
---> Package python-requests.noarch 0:1.1.0-4.el6 will be an update
---> Package python-zmq.x86_64 0:2.2.0.1-1.el6 will be installed
--> Processing Dependency: libzmq.so.3()(64bit) for package: python-zmq-2.2.0.1-1.el6.x86_64
---> Package yum-utils.noarch 0:1.1.30-17.el6_5 will be installed
--> Running transaction check
---> Package python-babel.noarch 0:0.9.4-5.1.el6 will be installed
---> Package zeromq3.x86_64 0:3.2.4-1.el6 will be installed
--> Processing Dependency: libpgm-5.1.so.0()(64bit) for package: zeromq3-3.2.4-1.el6.x86_64
--> Running transaction check
---> Package ope
npgm.x86_64 0:5.1.118-3.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package               Arch         Version                Repository      Size
================================================================================
Installing:
 python-crypto         x86_64       2.0.1-22.el6           os             158 k
 python-jinja2         x86_64       2.2.1-2.el6_5          optional       466 k
 python-msgpack        x86_64       0.1.13-3.el6           epel            29 k
 python-zmq            x86_64       2.2.0.1-1.el6          epel           424 k
 yum-utils             noarch       1.1.30-17.el6_5        updates        101 k
Updating:
 python-requests       noarch       1.1.0-4.el6            epel            71 k
Installing for dependencies:
 openpgm               x86_64       5.1.118-3.el6          epel           165 k
 python-babel          noarch       0.9.4-5.1.el[DEBUG   ] npgm.x86_64 0:5.1.118-3.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package               Arch         Version                Repository      Size
================================================================================
Installing:
 python-crypto         x86_64       2.0.1-22.el6           os             158 k
 python-jinja2         x86_64       2.2.1-2.el6_5          optional       466 k
 python-msgpack        x86_64       0.1.13-3.el6           epel            29 k
 python-zmq            x86_64       2.2.0.1-1.el6          epel           424 k
 yum-utils             noarch       1.1.30-17.el6_5        updates        101 k
Updating:
 python-requests       noarch       1.1.0-4.el6            epel            71 k
Installing for dependencies:
 openpgm               x86_64       5.1.118-3.el6          epel           165 k
 python-babel          noarch       0.9.4-5.1.el
6          os             1.4 M
 zeromq3               x86_64       3.2.4-1.el6            epel           334 k

Transaction Summary
================================================================================
Install       8 Package(s)
Upgrade       1 Package(s)

Total size: 3.1 M
Total download size: 1.3 M
Downloading Packages:
[DEBUG   ] 6          os             1.4 M
 zeromq3               x86_64       3.2.4-1.el6            epel           334 k

Transaction Summary
================================================================================
Install       8 Package(s)
Upgrade       1 Package(s)

Total size: 3.1 M
Total download size: 1.3 M
Downloading Packages:
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
    info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
    info = client.create(provider, names, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
    mapper.create(vm_))
  File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1162, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 775, in create
    ret = salt.utils.cloud.bootstrap(vm_, __opts__)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204, in deploy_script
    deploy_command
SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed

[INFO    ] Completed state [test.saltstackdev] at time 12:17:08.739060
nitin-salt-develop:
----------
          ID: test.aws
    Function: cloud.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
                  info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
                  info = client.create(provider, names, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
                  mapper.create(vm_))
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1162, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line 1899, in create
                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418, in bootstrap
                  deployed = deploy_script(**deploy_kwargs)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204, in deploy_script
                  deploy_command
              SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed
     Started: 12:07:40.764628
     Duration: 982 ms
     Changes:   
----------
          ID: test.autosandbox1
    Function: cloud.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
                  info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
                  info = client.create(provider, names, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
                  mapper.create(vm_))
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1162, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 775, in create
                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418, in bootstrap
                  deployed = deploy_script(**deploy_kwargs)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204, in deploy_script
                  deploy_command
              SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed
     Started: 12:09:45.748268
     Duration: 664 ms
     Changes:   
----------
          ID: test.saltstackdev
    Function: cloud.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106, in present
                  info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line 202, in create
                  info = client.create(provider, names, **kwargs)
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 362, in create
                  mapper.create(vm_))
                File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line 1162, in create
                  output = self.clouds[func](vm_)
                File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py", line 775, in create
                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418, in bootstrap
                  deployed = deploy_script(**deploy_kwargs)
                File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204, in deploy_script
                  deploy_command
              SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh -c /tmp/.saltcloud' failed
     Started: 12:11:06.413986
     Duration: 325 ms
     Changes:   

Summary
------------
Succeeded: 0
Failed:    3
------------
Total states run:     3
```

**Comment by s0undt3ch** [comment]
On 16 de Junho de 2014 17:21:13 WEST, Nitin Madhok notifications@github.com wrote:

> Still fails using this bootstrap-script. I tried to test it by creating
> an instance on AWS and two instances on our local OpenStack
> implementation. Here's the log:
> 
> ```
> *  INFO: /bin/sh /tmp/.saltcloud/deploy.sh -- Version 2014.04.16
> *  WARN: Running the unstable version of bootstrap-salt.sh
> 
> *  INFO: System Information:
> *  INFO:   CPU:          GenuineIntel
> *  INFO:   CPU Arch:     x86_64
> *  INFO:   OS Name:      Linux
> *  INFO:   OS Version:   2.6.32-431.1.2.el6.x86_64
> *  INFO:   Distribution: <R>ed <H>at <E>nterprise <L>inux 6.5
> 
> *  INFO: Installing minion
> *  INFO: Found function install_red_hat_enterprise_linux_stable_deps
> *  INFO: Found function config_salt
> [DEBUG   ]  *  INFO: /bin/sh /tmp/.saltcloud/deploy.sh -- Version
> 2014.04.16
> *  WARN: Running the unstable version of bootstrap-salt.sh
> 
> *  INFO: System Information:
> *  INFO:   CPU:          GenuineIntel
> *  INFO:   CPU Arch:     x86_64
> *  INFO:   OS Name:      Linux
> *  INFO:   OS Version:   2.6.32-431.1.2.el6.x86_64
> *  INFO:   Distribution: <R>ed <H>at <E>nterprise <L>inux 6.5
> 
> *  INFO: Installing minion
> *  INFO: Found function install_red_hat_enterprise_linux_stable_deps
> *  INFO: Found function config_salt
> *  INFO: Found function install_red_hat_enterprise_linux_stable
> *  INFO: Found function install_red_hat_enterprise_linux_stable_post
> *  INFO: Found function
> install_red_hat_enterprise_linux_restart_daemons
> *  INFO: Found function daemons_running
> *  INFO: Running install_red_hat_enterprise_linux_stable_deps()
> *  INFO: Installing 'yum-tsflags' to test for package installation
> success
> [DEBUG   ]  *  INFO: Found function
> install_red_hat_enterprise_linux_stable
> *  INFO: Found function install_red_hat_enterprise_linux_stable_post
> *  INFO: Found function
> install_red_hat_enterprise_linux_restart_daemons
> *  INFO: Found function daemons_running
> *  INFO: Running install_red_hat_enterprise_linux_stable_deps()
> *  INFO: Installing 'yum-tsflags' to test for package installation
> success
> Loaded plugins: product-id, subscription-manager
> This system is not registered to Red Hat Subscription Management. You
> can use subscription-manager to register.
> [DEBUG   ] Loaded plugins: product-id, subscription-manager
> This system is not registered to Red Hat Subscription Management. You
> can use subscription-manager to register.
> Setting up Install Process
> [DEBUG   ] Setting up Install Process
> Resolving Dependencies
> --> Running transaction check
> ---> Package yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5 will be
> installed
> [DEBUG   ] Resolving Dependencies
> --> Running transaction check
> ---> Package yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5 will be
> installed
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ================================================================================
> Package                 Arch        Version                Repository  
>  Size
> ================================================================================
> Installing:
> yum-plugin-tsflags      noarch      1.1.30-17.el6_5        optional    
>  20 k
> 
> Transaction Summary
> ================================================================================
> Install       1 Package(s)
> 
> Total download size: 20 k
> Installed size: 20 k
> Downloading Packages:
> Running rpm_check_debug
> Running Transaction Test
> Transaction Test Succeeded
> Running Transaction
> [DEBUG   ] --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ================================================================================
> Package                 Arch        Version                Repository  
>  Size
> ================================================================================
> Installing:
> yum-plugin-tsflags      noarch      1.1.30-17.el6_5        optional    
>  20 k
> 
> Transaction Summary
> ================================================================================
> Install       1 Package(s)
> 
> Total download size: 20 k
> Installed size: 20 k
> Downloading Packages:
> Running rpm_check_debug
> Running Transaction Test
> Transaction Test Succeeded
> Running Transaction
> Installing : yum-plugin-tsflags-1.1.30-17.el6_5.noarch                 
>  1/1[DEBUG   ] 
> 
> Verifying  : yum-plugin-tsflags-1.1.30-17.el6_5.noarch                 
>  1/1[DEBUG   ]  
> Verifying  : yum-plugin-tsflags-1.1.30-17.el6_5.noarch                 
>  1/1
> 
> 
> Installed:
> yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5                            
> 
> 
> Complete!
> [DEBUG   ]  
> 
> Installed:
> yum-plugin-tsflags.noarch 0:1.1.30-17.el6_5                            
> 
> 
> Complete!
> Loaded plugins: product-id, subscription-manager, tsflags
> This system is not registered to Red Hat Subscription Management. You
> can use subscription-manager to register.
> Setting up Install Process
> [DEBUG   ] Loaded plugins: product-id, subscription-manager, tsflags
> This system is not registered to Red Hat Subscription Management. You
> can use subscription-manager to register.
> Setting up Install Process
> Package chkconfig-1.3.49.3-2.el6_4.1.x86_64 already installed and
> latest version
> Package matching PyYAML-3.10-3.el6.x86_64 already installed. Checking
> for update.
> Package m2crypto-0.20.2-9.el6.x86_64 already installed and latest
> version
> [DEBUG   ] Package chkconfig-1.3.49.3-2.el6_4.1.x86_64 already
> installed and latest version
> Package matching PyYAML-3.10-3.el6.x86_64 already installed. Checking
> for update.
> Package m2crypto-0.20.2-9.el6.x86_64 already installed and latest
> version
> Resolving Dependencies
> --> Running transaction check
> ---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be installed
> ---> Package python-jinja2.x86_64 0:2.2.1-2.el6_5 will be installed
> --> Processing Dependency: python-babel >= 0.8 for package:
> python-jinja2-2.2.1-2.el6_5.x86_64
> ---> Package python-msgpack.x86_64 0:0.1.13-3.el6 will be installed
> ---> Package python-requests.noarch 0:1.1.0-3.1.1.el6 will be updated
> ---> Package python-requests.noarch 0:1.1.0-4.el6 will be an update
> ---> Package python-zmq.x86_64 0:2.2.0.1-1.el6 will be installed
> --> Processing Dependency: libzmq.so.3()(64bit) for package:
> python-zmq-2.2.0.1-1.el6.x86_64
> ---> Package yum-utils.noarch 0:1.1.30-17.el6_5 will be installed
> --> Running transaction check
> ---> Package python-babel.noarch 0:0.9.4-5.1.el6 will be installed
> ---> Package zeromq3.x86_64 0:3.2.4-1.el6 will be installed
> --> Processing Dependency: libpgm-5.1.so.0()(64bit) for package:
> zeromq3-3.2.4-1.el6.x86_64
> --> Running transaction check
> ---> Package ope[DEBUG   ] Resolving Dependencies
> --> Running transaction check
> ---> Package python-crypto.x86_64 0:2.0.1-22.el6 will be installed
> ---> Package python-jinja2.x86_64 0:2.2.1-2.el6_5 will be installed
> --> Processing Dependency: python-babel >= 0.8 for package:
> python-jinja2-2.2.1-2.el6_5.x86_64
> ---> Package python-msgpack.x86_64 0:0.1.13-3.el6 will be installed
> ---> Package python-requests.noarch 0:1.1.0-3.1.1.el6 will be updated
> ---> Package python-requests.noarch 0:1.1.0-4.el6 will be an update
> ---> Package python-zmq.x86_64 0:2.2.0.1-1.el6 will be installed
> --> Processing Dependency: libzmq.so.3()(64bit) for package:
> python-zmq-2.2.0.1-1.el6.x86_64
> ---> Package yum-utils.noarch 0:1.1.30-17.el6_5 will be installed
> --> Running transaction check
> ---> Package python-babel.noarch 0:0.9.4-5.1.el6 will be installed
> ---> Package zeromq3.x86_64 0:3.2.4-1.el6 will be installed
> --> Processing Dependency: libpgm-5.1.so.0()(64bit) for package:
> zeromq3-3.2.4-1.el6.x86_64
> --> Running transaction check
> ---> Package ope
> npgm.x86_64 0:5.1.118-3.el6 will be installed
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ================================================================================
> Package               Arch         Version                Repository   
>  Size
> ================================================================================
> Installing:
> python-crypto         x86_64       2.0.1-22.el6           os           
> 158 k
> python-jinja2         x86_64       2.2.1-2.el6_5          optional     
> 466 k
> python-msgpack        x86_64       0.1.13-3.el6           epel         
>  29 k
> python-zmq            x86_64       2.2.0.1-1.el6          epel         
> 424 k
> yum-utils             noarch       1.1.30-17.el6_5        updates      
> 101 k
> Updating:
> python-requests       noarch       1.1.0-4.el6            epel         
>  71 k
> Installing for dependencies:
> openpgm               x86_64       5.1.118-3.el6          epel         
> 165 k
> python-babel          noarch       0.9.4-5.1.el[DEBUG   ] npgm.x86_64
> 0:5.1.118-3.el6 will be installed
> --> Finished Dependency Resolution
> 
> Dependencies Resolved
> 
> ================================================================================
> Package               Arch         Version                Repository   
>  Size
> ================================================================================
> Installing:
> python-crypto         x86_64       2.0.1-22.el6           os           
> 158 k
> python-jinja2         x86_64       2.2.1-2.el6_5          optional     
> 466 k
> python-msgpack        x86_64       0.1.13-3.el6           epel         
>  29 k
> python-zmq            x86_64       2.2.0.1-1.el6          epel         
> 424 k
> yum-utils             noarch       1.1.30-17.el6_5        updates      
> 101 k
> Updating:
> python-requests       noarch       1.1.0-4.el6            epel         
>  71 k
> Installing for dependencies:
> openpgm               x86_64       5.1.118-3.el6          epel         
> 165 k
> python-babel          noarch       0.9.4-5.1.el
> 6          os             1.4 M
> zeromq3               x86_64       3.2.4-1.el6            epel         
> 334 k
> 
> Transaction Summary
> ================================================================================
> Install       8 Package(s)
> Upgrade       1 Package(s)
> 
> Total size: 3.1 M
> Total download size: 1.3 M
> Downloading Packages:
> [DEBUG   ] 6          os             1.4 M
> zeromq3               x86_64       3.2.4-1.el6            epel         
> 334 k
> 
> Transaction Summary
> ================================================================================
> Install       8 Package(s)
> Upgrade       1 Package(s)
> 
> Total size: 3.1 M
> Total download size: 1.3 M
> Downloading Packages:
> [ERROR   ] An exception occurred in this state: Traceback (most recent
> call last):
> File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in
> call
>    **cdata['kwargs'])
> File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106,
> in present
>    info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line
> 202, in create
>    info = client.create(provider, names, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 362, in create
>    mapper.create(vm_))
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 1162, in create
>    output = self.clouds[func](vm_)
> File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py",
> line 775, in create
>    ret = salt.utils.cloud.bootstrap(vm_, __opts__)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418,
> in bootstrap
>    deployed = deploy_script(**deploy_kwargs)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204,
> in deploy_script
>    deploy_command
> SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh
> -c /tmp/.saltcloud' failed
> 
> [INFO    ] Completed state [test.saltstackdev] at time 12:17:08.739060
> nitin-salt-develop:
> ----------
>          ID: test.aws
>    Function: cloud.present
>      Result: False
> Comment: An exception occurred in this state: Traceback (most recent
> call last):
> File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in
> call
>                  **cdata['kwargs'])
> File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106,
> in present
>        info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line
> 202, in create
>                  info = client.create(provider, names, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 362, in create
>                  mapper.create(vm_))
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 1162, in create
>                  output = self.clouds[func](vm_)
> File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/ec2.py", line
> 1899, in create
>                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418,
> in bootstrap
>                  deployed = deploy_script(**deploy_kwargs)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204,
> in deploy_script
>                  deploy_command
> SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh
> -c /tmp/.saltcloud' failed
>     Started: 12:07:40.764628
>     Duration: 982 ms
>     Changes:   
> ----------
>          ID: test.autosandbox1
>    Function: cloud.present
>      Result: False
> Comment: An exception occurred in this state: Traceback (most recent
> call last):
> File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in
> call
>                  **cdata['kwargs'])
> File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106,
> in present
>        info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line
> 202, in create
>                  info = client.create(provider, names, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 362, in create
>                  mapper.create(vm_))
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 1162, in create
>                  output = self.clouds[func](vm_)
> File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py",
> line 775, in create
>                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418,
> in bootstrap
>                  deployed = deploy_script(**deploy_kwargs)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204,
> in deploy_script
>                  deploy_command
> SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh
> -c /tmp/.saltcloud' failed
>     Started: 12:09:45.748268
>     Duration: 664 ms
>     Changes:   
> ----------
>          ID: test.saltstackdev
>    Function: cloud.present
>      Result: False
> Comment: An exception occurred in this state: Traceback (most recent
> call last):
> File "/usr/lib/python2.6/site-packages/salt/state.py", line 1492, in
> call
>                  **cdata['kwargs'])
> File "/usr/lib/python2.6/site-packages/salt/states/cloud.py", line 106,
> in present
>        info = __salt__['cloud.create'](cloud_provider, name, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/modules/cloud.py", line
> 202, in create
>                  info = client.create(provider, names, **kwargs)
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 362, in create
>                  mapper.create(vm_))
> File "/usr/lib/python2.6/site-packages/salt/cloud/__init__.py", line
> 1162, in create
>                  output = self.clouds[func](vm_)
> File "/usr/lib/python2.6/site-packages/salt/cloud/clouds/openstack.py",
> line 775, in create
>                  ret = salt.utils.cloud.bootstrap(vm_, __opts__)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 418,
> in bootstrap
>                  deployed = deploy_script(**deploy_kwargs)
> File "/usr/lib/python2.6/site-packages/salt/utils/cloud.py", line 1204,
> in deploy_script
>                  deploy_command
> SaltCloudSystemExit: Executing the command '/tmp/.saltcloud/deploy.sh
> -c /tmp/.saltcloud' failed
>     Started: 12:11:06.413986
>     Duration: 325 ms
>     Changes:   
> 
> Summary
> ------------
> Succeeded: 0
> Failed:    3
> ------------
> Total states run:     3
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/saltstack/salt-bootstrap/pull/405#issuecomment-46200218

I'll investigate further first thing tomorrow.

Same AMI correct?
Pedro Algarvio @ Phone

**Comment by nmadhok** [comment]
Well AMI (Amazon Machine Image) is a special type of virtual appliance used to create a VM within Amazon EC2. So not the same AMI. But the same image (RHEL 6.5).

**Comment by ghost** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap/job/pr/job/build/33/

**Comment by s0undt3ch** [comment]
Could you please try again with https://raw.githubusercontent.com/s0undt3ch/salt-bootstrap/develop/bootstrap-salt.sh

**Comment by nmadhok** [comment]
Works with: https://raw.githubusercontent.com/s0undt3ch/salt-bootstrap/develop/bootstrap-salt.sh 

Tested using 
1. RHEL6.5 on OpenStack, AWS 
2. CentOS6.5 on DigitalOcean

**Comment by s0undt3ch** [comment]
Awesome!

**Pull request merged**
