### PR TITLE
Install a `pyzmq` package compiled against `libzmq3`. Fixes #57.

### LINKED ISSUE #57: libzmq3 packages for debian 6
Debian 6 (and 7) comes with libzmq1, not libzmq3. This version doesn't support keepalive and is thus pretty worthless (we loose half our minions in a day). Ubuntu doesn't have this problem since it comes with libzmq3.

I have created 2 debian 6 packages:
libzmq3_3.2.2_amd64.deb
python-zmq_2.2.0.1_amd64.deb

After installing those, I run the bootstrap and the minion is successfully installed using libzmq3. 
Who should I send those (or a howto for making them) ?

### PR DESCRIPTION
**Pull request by s0undt3ch**
Although Debian experimental has `libzmq3`, it does not have `pyzmq` compiled against it. We install `pyzmq` from `pip` having `libzmq3` already installed.

**Should we really do this?**
**Even the stable builds are installing `pyzmq` from pip.**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
@saltstack opinions?

**Comment by techhat** [comment]
Not being a Debian user, and therefore probably not qualified to say anything, I am okay with this.

**Comment by ghost** [comment]
Wow.. so you're melding the available libzmq3 from experimental with a pip-installed pyzmq that can support zmq3? Good workaround!

**Comment by s0undt3ch** [comment]
Well, yes, it seems that a pyzmq compiled against ZMQ3 is going to take a long time...

I'm also having the users pass an extra flag just for that so they know what their doin'...

**Comment by s0undt3ch** [comment]
Let's solve one of Debian's support current issues.

**Pull request merged**
