### PR TITLE
Fix linux distribution detection

### PR DESCRIPTION
**Pull request by GuillaumeDerval**
Among other things, this commit fixes detection of RHEL 7 Beta/RC.

### CODE REVIEW

**Comment by ghost** [comment]
Merged build triggered.

**Comment by ghost** [comment]
Merged build started.

**Comment by ghost** [comment]
Merged build finished.

**Comment by ghost** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap/job/pr/job/build/23/

**Comment by s0undt3ch** [comment]
This "switch" seems that it's going to cause some issues. Why wasn't it being properly detected?

Can you paste the output of:

```
sudo find /etc/ -name '*-release' -print -exec cat {} \;
which lsb_release && lsb_release -a
```

**Comment by s0undt3ch** [comment]
WOW! This bug exists ever since 2013-02-22!!!! Wonder how we never got hit by it...

**Comment by s0undt3ch** [comment]
Thank You!

**Pull request merged**
