### PR TITLE
use official amazon linux 2 repo for amazon linux 2

### PR DESCRIPTION
**Pull request by mchugh19**
### What does this PR do?
~"Supports" Amazon Linux 2 by using the saltstack centos7 yum repo
Don't know if this is an upstream-able change, but it works for us.~
Update to use new amazon linux 2 yum repo

### What issues does this PR fix or reference?
#1194

### Previous Behavior
bootstrap-salt.sh fails on amazon linux 2

### New Behavior
bootstrap-salt.sh successfully installs and runs salt-minion

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @mchugh19! My apologies for taking so long to respond here. I see you have a checkstyle error that needs to be fixed.

However, the salt repo has added amazon linux 2 support now: http://repo.saltstack.com/#amzn

I think we should use the official packages, rather than the CentOS 7 method you've provided here. Thoughts?

**Comment by mchugh19** [comment]
I think this should resolve the lint error and also use the new official amazon linux 2 repo. 

I wouldn't mind a double-check on this as I don't have the ability to spin up an ec2 instance at the moment, and it is copying a large block of code from the amazon linux 1 deps function (with some package name updates).

**Comment by rallytime** [comment]
Hey @mchugh19 - I added a test to our runner for the new amazonlinux 2 builds and it looks like there's an error here. The test is failing. Can you take a look?

https://travis-ci.com/saltstack/salt-bootstrap/jobs/158212816

**Comment by mchugh19** [comment]
@rallytime Gah! Looks like it was a missing trailing slash typo. Let's see how travis likes this version...

**Comment by mchugh19** [comment]
Looks like the minion was successfully installed in the amazon linux 2 test, but had an issue on the integration tests. So I think it validated what this PR covers, but let me know if something else is needed.

**Comment by rallytime** [comment]
@mchugh19 The reason this is failing is because you didn't add support for the `git` install options, only the stable options. So something like `sh bootstrap-salt.sh git v2018.3.3` isn't working. The minion and master daemons can't start because there are packages missing. Would you be willing to add support for the git option as well? There should be some examples to follow of amazon linux 1 that just need to be adapted a bit for amazon linux 2.

The stable options are working swimmingly! So thank you for adding that support.

**Comment by rallytime** [comment]
@mchugh19 Getting closer! Thank you for adding that support. Looks like a couple of tweaks may still be needed: https://travis-ci.com/saltstack/salt-bootstrap/jobs/158600374

**Comment by mchugh19** [comment]
Setup free tier aws to validate amazon linux 2. Git installs should be fixed now.

**Comment by rallytime** [comment]
This looks great! Thanks @mchugh19!

**Review by rallytime — APPROVED** [review]

**Pull request merged**
