### PR TITLE
Support Debian 8 Jessie

### PR DESCRIPTION
**Pull request by mafrosis**
..

### CODE REVIEW

**Comment by mafrosis** [comment]
Hey @s0undt3ch. The build above failed, but the details link 404's. I tried running the tests locally, but I get `ImportError: No module named ext.os_data` from `./install-testsuite-deps.py`

**Comment by s0undt3ch** [comment]
Don't worry about the failures above. They're caused by a new Jenkins instance that I'm still developing....

Need to setup a test project just for this purpose...

**Comment by s0undt3ch** [comment]
Sorry for being slow here.

Thanks!

**Comment by mafrosis** [comment]
Awesome!

**Pull request merged**
