### PR TITLE
Install the Debian keys

### PR DESCRIPTION
**Pull request by s0undt3ch**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap-pr/4/

**Comment by s0undt3ch** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap-pr/6/

**Comment by jsplink** [comment]
not sure if #361 would be better placement... same ticket though

**Comment by s0undt3ch** [comment]
Dam! It wasn't a ticket, it was a pull request... I'll take care of this.

**Comment by jsplink** [comment]
fyi - http://pastebin.com/qzLjjBdJ

**Comment by s0undt3ch** [comment]
Test FAILed.
Refer to this link for build results: http://cookingwithsalt.org/job/bootstrap-pr/8/

**Pull request merged**
