### PR TITLE
Add support to install on Ubuntu 24.04 Noble Numbat

### PR DESCRIPTION
**Pull request by sblaisot**
### What does this PR do?

This PR add support for salt 3007 installation as onedir or stable package on Ubuntu 24.04 Noble Numbat using salt's Ubuntu 24.04 repositories.

It currently only support salt 3007 as other versions are not available in saltstack's Ubuntu 24.04 repos

### Previous Behavior

Installation failure on Ubuntu 24.04

### New Behavior

Installation works on Ubuntu 24.04

### CODE REVIEW

**Comment by sblaisot** [comment]
@dmurphy18 any news on this?

**Comment by EHJ-52n** [comment]
I would recommend to change the default version to the latest supported, hence `noble` and not `trusty`.

```
        *)
            DISTRO_CODENAME="noble"
            ;;
```

**Comment by sblaisot** [comment]
> I would recommend to change the default version to the latest supported, hence `nobel` and not `trusty`.
> 
> ```
>         *)
>             DISTRO_CODENAME="noble"
>             ;;
> ```

This is unrelated to this PR and subject to various side-effects I can not anticipate so I would prefer this to be done in another PR.

**Comment by dmurphy18** [comment]
Work is ongoing to add support for Ubuntu 24.04 in https://github.com/saltstack/salt-bootstrap/pull/1987.
Don't want to duplicate work and testing.

**Comment by Foorack** [comment]
> Work is ongoing to add support for Ubuntu 24.04 in #1987. Don't want to duplicate work and testing.

Maybe, although the changes in that PR are quite substansive and bigger in scope. Considering Ubuntu 24.04 has been released for two months now, it would be nice to support it as quick as possible.

**Comment by dmurphy18** [comment]
@Foorack Given the recent reduction in resources (personal) since the Broadcom acquisition, time has become limited, and I am close with the PR under development.  Given the bootstrap script is a simple bash script, it would be easy to change the selection of 'trusty' to 'noble'  in your copy as a work-around.

The Salt Core don't have unlimited time, hence concentration on PR's under development at the moment.

**Comment by Kenneth-Sills** [comment]
I'm inclined to agree with @Foorack, salt bootstrapping is broken for common Ubuntu and Debian LTS setups and has been for months. The refactor is going to be great and is much needed for sure, but these changes are a couple of lines while the refactor is thousands of lines of changes and AFAICT hasn't started a real review yet.

With limited resources, it seems like it would make sense to take care of the bite-size fix PRs since that larger refactor and review could take weeks or months yet to see release, and may need its own patch cycles to see stability.

I hope I don't come off as argumentative, we obviously appreciate the hard work you're putting in and understand the struggle you're navigating! And, naturally, I'm biased given #1995. 😆

**Comment by dmurphy18** [comment]
@Kenneth-Sills @Foorack @sblaisot Re-working the PR to not remove kitchen, so that I can get this out quicker.
Note: even the develop branch has lint issues, so not so simple as just adding 'noble' for Ubuntu 24.04, The develop branch needs work too.

Working through test failures on https://github.com/saltstack/salt-bootstrap/pull/1987 at the moment, so soon.

**Comment by dmurphy18** [comment]
@sblaisot Closing this PR since PR https://github.com/saltstack/salt-bootstrap/pull/1987 has been merged which supports Ubuntu 24.04, along with fixing a number of other issues with the bootstrap script on the develop branch.  A new release has been cut and  is in stable (2024-07-12) and waiting for the web site to sync up at the moment from the S3 bucket, see https://github.com/saltstack/salt-bootstrap/actions/runs/9910182797.

If there are any issues with closing this PR please let me know and it can be re-opened or a new issue generated to resolve the issue.

**Pull request closed without merging**
