### PR TITLE
ci: add `fedora-37` & `fedora-38`

### PR DESCRIPTION
**Pull request by myii**
### What does this PR do?

Fedora 37 packages are available at the [Fedora Updates System](https://bodhi.fedoraproject.org/updates/?search=salt-30), so adding it to the CI here.

The other commit is replacing the Python 3.10 specific `pyzmq` package on Tumbleweed with the virtual one -- as suggested by @agraul when discussing the situation on Slack.

### CODE REVIEW

**Comment by myii** [comment]
This was working back in late June when I tried it:

* https://github.com/myii/salt-bootstrap/actions/runs/2537833986

However, now held up by the update to Python 3.11:

```console
Error: 
 Problem: conflicting requests
  - nothing provides python(abi) = 3.10 needed by python3-m2crypto-0.38.0-2.fc35.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
 * ERROR: Failed to run install_fedora_deps()!!!
```

As mentioned in point 5 at https://fedoraproject.org/wiki/Changes/Python3.11#Scope:

> 5. Mass rebuild all the packages that runtime require `python(abi) = 3.10` and/or `libpython3.10.so.1.0` (~3800 known packages in October 2021)

**Review by agraul — APPROVED** [review]
The TW related change looks good!

**Review by garethgreenaway — APPROVED** [review]

**Comment by garethgreenaway** [comment]
@myii Looks like you've got a merge conflict here.

**Comment by myii** [comment]
Rebased this PR and added Fedora 38 as well, as discussed with @garethgreenaway in Slack.  Included a temporary commit to avoid `git` builds on Fedora 37+ for now, until those are fixed.

Short overview showing the two new instances added to the matrix:

* https://github.com/myii/salt-bootstrap/actions/runs/3655168532

---

In terms of the failures, looks like it's due to a `setuptools` deprecation:

```console
/usr/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```

Which refers back to this section:

* https://github.com/saltstack/salt-bootstrap/blob/7a4f2ca0e265963a712baa81536cae95041788a5/bootstrap-salt.sh#L4298-L4302

The working version of `setuptools` on Fedora 36:

```console
python3-setuptools             noarch     59.6.0-3.fc36      updates     934 k
```

While the version on Fedora 37 is:

```console
python3-setuptools             noarch     62.6.0-2.fc37      fedora      1.6 M
```

Just looking through the Salt repo, the workaround there appears to be to pin the version of `setuptools`:

* https://github.com/saltstack/salt/pull/61244

That's not a long-term solution, though -- so eventually going to have to do what the message says:

```console
Use build and pip and other standards-based tools.
```

**Review by garethgreenaway — APPROVED** [review]

**Pull request merged**
