### PR TITLE
Use native repositories for Debian 11

### PR DESCRIPTION
**Pull request by jpacura**
Remove best-effort support for Debian Testing
Remove Ubuntu 20.10 support because it is end-of-life

### What does this PR do?
This PR will use the Debian 11 repositories and packages when executed on Debian 11, instead of Debian 10 repositories and packages. 

This PR also removes best-effort support for Debian Testing.

This PR also removes support for Ubuntu 20.10, which is now end-of-life.

### What issues does this PR fix or reference?
https://github.com/saltstack/salt-bootstrap/issues/1614

### Previous Behavior
Running the script on Debian 11 would configure the Debian 10 repositories, and install the Debian 10 packages

### New Behavior
Running the script on Debian 11 will configure the Debian 11 repositories, and install the Debian 11 packages

### CODE REVIEW

**Comment by jpacura** [comment]
Some of the Debian 11 tests failed because the earliest version in the repos for Debian 11 is 3004, but some of the tests are configured to use 3003 and 3002, which do not exist for Debian 11. If anyone more familiar with the checks can fix this for me, I would appreciate it. I will also try and figure it out myself tomorrow

**Comment by smitelli** [comment]
I checked out this PR and it worked flawlessly for my use case (installation on a vanilla Debian 11.1 VM).

Pasting some version info in case anyone wants to examine further:

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
$ cat /etc/debian_version
11.1
```

```
$ ./bootstrap_salt.sh -X -F -c /tmp
...snip...
 *  INFO: Running version: 2021.09.17
 *  INFO: Executed by:
 *  INFO: Command line: '/tmp/bootstrap_salt.sh -X -F -c /tmp'
 *  WARN: Running the unstable version of bootstrap-salt.sh
 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   5.10.0-9-amd64
 *  INFO:   Distribution: Debian 11
...snip...
```

```
$ salt-call --versions-report
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-9-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```

**Comment by jpacura** [comment]
Sorry I never got around to fixing the tests on this. Is there any reason why this isn't being reviewed?

**Comment by jpacura** [comment]
Sorry for force-pushing your merge away, but I noticed a typo in my commit message that made it a little confusing. I rebased it during this process, so it's ahead of origin/develop now too. I will try and fix the CI/CD if it fails again too. Thank you for bringing the PR up-to-date earlier

**Comment by jpacura** [comment]
I think I have fixed the CI/CD, and have rebased again, but I can't figure out why the workflow actions don't run for me. Can somebody please look into it for me? I don't think I have access rights to see what the problem is

**Comment by jpacura** [comment]
Looks like all the tests for Debian pass now. Is there anything else I need to do in order for this PR to be reviewed?

**Comment by krionbsd** [comment]
I don't want to add support for Debian 12 as it's not released yet, when it's released we'll provide the packages for that and will add bootstrap+CI support

**Comment by jpacura** [comment]
According to the readme for this repo, the script is supposed to support Debian 12 using Debian 11 packages
`This script provides best-effort support for the upcoming Debian testing release. Package repositories are not provided on SaltStack's Debian repository for Debian testing releases. However, the bootstrap script will attempt to install the packages for the current stable version of Debian.`

**Comment by krionbsd** [comment]
> According to the readme for this repo, the script is supposed to support Debian 12 using Debian 11 packages `This script provides best-effort support for the upcoming Debian testing release. Package repositories are not provided on SaltStack's Debian repository for Debian testing releases. However, the bootstrap script will attempt to install the packages for the current stable version of Debian.`

No, it's definitely a no-go for me as people will start using and installing salt on *non-supported* OS releases

**Comment by jpacura** [comment]
I didn't add that section to the README. The specification in the readme says that the script is to provide best-effort support for Debian Testing. The script uses the same justification for installing on Ubuntu non-LTS releases, such as 21.10, which is supported by the script despite not being a supported OS release for salt

**Comment by smitelli** [comment]
Just wanted to jump in here as the person who opened the [original issue](https://github.com/saltstack/salt-bootstrap/issues/1614):

The only reason installation on Debian 11 works _today_ is due to this type of future-proofing. Please give some thought to how things will be in two years when Debian 12 becomes stable and this script is using old switching logic that refuses it.

**Comment by myii** [comment]
I've tested out this PR in (my fork of) the [salt-image-builder](https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder) repo that's used by the SaltStack Formulas team:

* https://gitlab.com/myii/salt-image-builder/-/pipelines/448390851

The Debian 12 image is pulled from [Docker Hub](https://hub.docker.com/_/debian) using `debian:bookworm`.  The changes here appear to be working as expected.

The image builder also [logs various info about each image](https://gitlab.com/saltstack-formulas/infrastructure/salt-image-builder/-/tree/master/packages_versions), including the grains, packages and pips installed.  Comparing the Debian 11 before and after this PR is effectively identical.

However, there are some noteworthy differences when comparing Debian 11 and Debian 12 (specifically the grains):

```diff
--- debi-11.0-master-py3
+++ debi-12.0-master-py3
 # salt-call --local grains.item init kernel kernelrelease kernelversion locale_info lsb_distrib_codename lsb_distrib_id lsb_distrib_release os os_family osarch osbuild oscodename osfinger osfullname osmajorrelease osmanufacturer osrelease osrelease_info osversion pythonexecutable pythonpath pythonversion saltpath saltversion saltversioninfo systemd virtual virtual_subtype zmqversion
 local:
@@ -61,11 +61,10 @@
         timezone:
             unknown
     lsb_distrib_codename:
-        bullseye
     lsb_distrib_id:
         Debian
     lsb_distrib_release:
-        11
+        testing/unstable
     os:
         Debian
     os_family:
@@ -74,18 +73,17 @@
         amd64
     osbuild:
     oscodename:
-        bullseye
+        n/a
     osfinger:
-        Debian-11
+        Debian-testing/unstable
     osfullname:
         Debian
     osmajorrelease:
-        11
     osmanufacturer:
     osrelease:
-        11
+        testing/unstable
     osrelease_info:
-        - 11
+        - testing/unstable
     osversion:
     pythonexecutable:
         /usr/bin/python3
@@ -99,7 +97,7 @@
     pythonversion:
         - 3
         - 9
-        - 2
+        - 9
         - final
         - 0
     saltpath:
@@ -111,9 +109,9 @@
     systemd:
         ----------
         features:
-            +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified
+            +PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS -OPENSSL +ACL +BLKID +CURL +ELFUTILS -FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP -LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
         version:
-            247
+            249
     virtual:
         container
     virtual_subtype:
```

* Essentially, support for Debian 12 hasn't been added to Salt itself.

---

#### Suggestions

In respect to the discussion above, I believe all are in agreement with improving the Debian 11 support.  In terms of the Debian 12 support, the options appear to be:

1. Add it now, as proposed by this PR.
2. Add support for Debian 12 to Salt first and then add it here.
3. Same as [2] but wait until X months before the expected [release date](https://wiki.debian.org/DebianReleases) (probably some time around 2023 Q3).
4. Same as [3] but wait for the official release date to be set first (this may only be a few weeks before the actual release).

In all cases, I recommend that Debian 12 testing be added to the CI.

In my opinion, the first and last options are too early/late.  Any time after [2] seems about right.  Option [3] is based upon the time period when Debian 11 was added to this repo (in #1514).

However, this introduces the hassle of removing some lines now, only to reintroduce them at a later date.  Perhaps those can be included in a draft PR instead?

**Comment by jpacura** [comment]
I appreciate the feedback on this PR. I am not against removing Debian testing support from this PR so that we can at least get Debian 11 working properly. My personal preference if option 1 is not considered would be option number 3 because Debian 11 went stable months before the Salt repos were created for it, so we needed to use the Debian 10 repos on Debian 11 for quite a while despite it being stable. 

My main concern is that the README (which I consider the specification for the functionality of this script) establishes that best-effort support should exist for Debian Testing, and does not specify that this only exists right before Testing is about to become Stable. I did not add this to the README, so as far as I am aware, this was always the intended specification. 

I believe that the only reason that Debian 11 Testing support was added so late was because nobody needed to use it until I added it in my earlier PR. I was a little surprised to get such pushback on this PR, considering nobody took issue with this in my earlier PR.

 I often use Testing instead of Stable for servers that need newer versions of tools, where backports is not viable. I believe that the documentation was very explicit that this configuration is not supported by saltstack, so I did not consider it as a concern earlier, since I was aware I would get no support if something did not work. 

Again, I appreciate, and am happy to consider other options on this.

**Comment by myii** [comment]
Just remembered to check the `/etc/os-release` file.  The diff between Debian 11 and 12:

```diff
--- Debian 11
+++ Debian 12
@@ -1,8 +1,5 @@
-PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
+PRETTY_NAME="Debian GNU/Linux bookworm/sid"
 NAME="Debian GNU/Linux"
-VERSION_ID="11"
-VERSION="11 (bullseye)"
-VERSION_CODENAME=bullseye
 ID=debian
 HOME_URL="https://www.debian.org/"
 SUPPORT_URL="https://www.debian.org/support"
```

This explains why some grains are missing.  So not much can be done until the Debian folks add that in (in terms of "adding support to Salt").

In that case, it's really between options [1] and [3].

> 1. Add it now, as proposed by this PR.
> 2. ...
> 3. ... wait until X months before the expected release date (probably some time around 2023 Q3).

What determines the duration for option [3], @krionbsd?

**Comment by jpacura** [comment]
Please let me know on this, so I can make any changes that need to be done for merging this, @krionbsd

**Comment by krionbsd** [comment]
@jpacura @myii sorry for a delayed response because of my PTO, I would rather move with option 3, as we already did with Debian 11. We have to add the missing grains first for 12 into Salt. I'm really sorry you feel it's a pushback, I just don't want to give people a feeling they're safe to use Debian 11 packages on Debian 12, because they aren't, we will definitely release new versions soon and build the packages for Debian 11, but we give zero guarantee these packages work as intended on Debian 12.
If 12 is expected to be released on Q3 2023, I guess it might be a good idea to support it starting from Q1 2023. At this time point (Q1 2023) we might start looking at dependencies and full functionality and I would be extremely happy if you might help with those things. Thoughts on that?

**Comment by jpacura** [comment]
I hope you enjoyed your PTO, and I appreciate your response. I am a little busy this week, so I will modify this PR either this weekend, or early next week. The only other thing I can think of besides waiting until later to add back in Debian 12 support is to block it behind a command-line switch that makes sure the user understands that this is unsafe, but we can think about something like that in another issue and another PR, i'm not in that much of a hurry on it. I will remove Debian 12 best-effort support for now when I get a chance. I appreciate the input on this PR.

**Comment by jpacura** [comment]
I removed best-effort support for installing salt on Debian Testing, and I rebased this PR over the develop branch again. I believe that this PR is ready for rereview. Thanks everyone for the input and guidance on this PR

**Comment by jpacura** [comment]
Sorry to bump this, but I just want to make sure that I haven't forgotten to address something that is holding this up from being rereviewed.

**Review by krionbsd — APPROVED** [review]

**Pull request merged**
