### PR TITLE
fix  saltstack repo creation in SL5/6

### PR DESCRIPTION
**Pull request by kmkramer**
### What does this PR do?

creation of saltstack repo used $releasever. $releasever acts differently in sl5/sl6 than sl7 does
### What issues does this PR fix or reference?
#833
### Previous Behavior

https://repo.saltstack.com/yum/redhat/6.5/x86_64/latest/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
### New Behavior

yum repolist  returns as expected repo reachable
### Tests written?

No

### CODE REVIEW

**Comment by rallytime** [comment]
Hi @kmkramer - Thank you for submitting this pull request. I see that the issue you're referencing and wanting to fix with this PR seems to be resolved with the Scientific Linux mirroring that you've been discussing with @dmurphy18 in #833. Is this fix still needed? 

If this fix is still needed, I have some concerns here. It seems like this PR is touching much more code than it likely needs to, as it is changing some support for Debian/Ubuntu packages and is also removing some functionality such as the `-r` option. We do not want to remove that support. I'd like this fix to be more isolated to fixing the issue at hand of SL5/6 support.

If this fix is no longer needed because of package mirroring, then we can simply close this out.

**Comment by kmkramer** [comment]
It is probably how I did the pull request. The lines I changed were 3313-3325 specifically for the SL repo creation bits.

**Comment by rallytime** [comment]
Ah ok. So is this fix still needed? If so, can you redo/rebase this so that only the changes you made are present?

**Comment by kmkramer** [comment]
I believe so. I'm working on how to fix my fork.

**Comment by kmkramer** [comment]
gonna start over and resubmit at this point

**Comment by rallytime** [comment]
@kmkramer Sounds good. Thank you very much.

**Pull request closed without merging**
