### PR TITLE
Some minor tweaks, as discussed in ticket 225.

### PR DESCRIPTION
**Pull request by sdelmas**
1) Fixed wording on the -U option
2) Added a -K option to keep temporary files
3) Some tweaking with Ubuntu repository setup (11.04 logic seems to be off with respect to the -y choice). Made the adding of the universe dependent on it not being already there.

Open question… for older Ubuntu versions the archive location added for the universe seems wrong. The one I know is:

deb http://old-releases.ubuntu.com/ubuntu/ natty main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ natty-updates main restricted universe multiverse
deb http://old-releases.ubuntu.com/ubuntu/ natty-security main restricted universe multiverse

However, I did not change the code at this point as that seems like it should be tested independently (maybe my expectations here are off).

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Not going to merge this just yet because Travis complained about a timed out execution and I can't do more investigation with just my phone, will review again in some hours.

Anyway, Thank You for this contribution.

**Comment by s0undt3ch** [comment]
I merged your changes in #236

**Comment by sdelmas** [comment]
Cool, thx. Let me check the install again. It may be necessary to change the repo URL for older distributions.

**Comment by s0undt3ch** [comment]
The repo URL's are updated ;) Thanks for that info...

**Pull request closed without merging**
