### PR TITLE
Import CentOS 7 GPG key on RHEL for installing base dependencies from Salt corp repo

### PR DESCRIPTION
**Pull request by vutny**
This PR fixes GPG issues mentioned in #757, saltstack/salt#29094 and saltstack/salt#31193

### CODE REVIEW

**Comment by vutny** [comment]
Ping @jfindlay @s0undt3ch

**Comment by s0undt3ch** [comment]
Go Go Jenkins!

**Comment by vutny** [comment]
@s0undt3ch Do you have any built/test job configured for this project?

**Comment by vutny** [comment]
@s0undt3ch Is it possible to merge this? Thanks in advance!

**Comment by s0undt3ch** [comment]
Can you replace the `-o` with `||`? That's causing a lint error....

Need to make those Jenkins lint report appear on PRS...

**Comment by s0undt3ch** [comment]
We need to keep the script as POSIX compatible as possible.

**Comment by vutny** [comment]
@s0undt3ch Sure thing, fixed.

Just wandering, what tool are you using for lint checks? `shellcheck` didn't complain about that line for me.

By the way, I thought that using `[ expression1 -o expression2 ]` syntax is supported by POSIX... This works in `dash` that claims to be a fully POSIX-compliant implementation of /bin/sh.

And there are still some cases in the script...

``` sh
  1957     if [ "$CPU_ARCH_L" = "amd64" -o "$CPU_ARCH_L" = "x86_64" ]; then
...
  1959     elif [ "$CPU_ARCH_L" = "i386" -o "$CPU_ARCH_L" = "i686" ]; then
```

**Comment by s0undt3ch** [comment]
Hmm... Shellsheck is now throwing some additional issues

https://jenkins-testing.saltstack.com/job/bootstrap/job/pr/job/765/job/lint/violations/

And they don't seem related to your changes...

**Pull request merged**
